<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Fragrance</name>
   <tag></tag>
   <elementGuidId>5f6e6cce-68fb-47bd-8d4e-729772181d50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='nav']/li[2]/div/div/div[8]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Fragrance&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fda434fb-4bfc-4e5c-8282-2245fa5c59df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-1208550441 avenir-black</value>
      <webElementGuid>f7d7e28c-29b9-4cf5-b361-32dfb337abc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/home-living/fragrance</value>
      <webElementGuid>620e6df4-38ee-4612-a798-c192b47bae2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fragrance</value>
      <webElementGuid>fd2ccfc4-c957-41d1-a156-1e5686dcf852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav&quot;)/li[@class=&quot;jsx-1208550441 nav-item&quot;]/div[@class=&quot;jsx-1208550441 mega-menu row&quot;]/div[@class=&quot;jsx-1208550441 nav-column row col-lg-12 col-md-12 col-sm-12&quot;]/div[@class=&quot;jsx-1208550441 list-item col-lg-3 col-md-4 col-sm-6&quot;]/a[@class=&quot;jsx-1208550441 avenir-black&quot;]</value>
      <webElementGuid>3b9b43b9-15a2-4777-9f00-76c254c73990</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='nav']/li[2]/div/div/div[8]/a</value>
      <webElementGuid>cabc779a-2b34-467e-89b0-ab598b37dab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Fragrance')]</value>
      <webElementGuid>0184fe92-a3e1-489d-89e9-ea6bd6e41401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cutleries'])[1]/following::a[1]</value>
      <webElementGuid>283a15d9-19ce-49dc-800c-9fb730005b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Handuk Mandi'])[1]/following::a[2]</value>
      <webElementGuid>5ca28da0-a604-4662-9b57-b760145d5aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Koper'])[1]/preceding::a[1]</value>
      <webElementGuid>a55b0da7-5a11-4470-80ed-dcd0a0b20314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Health &amp; Beauty'])[1]/preceding::a[2]</value>
      <webElementGuid>6e50f8bb-22bb-492e-b4fc-f239f394f916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fragrance']/parent::*</value>
      <webElementGuid>64a3b578-14a7-458d-a235-b6a4400b2f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/home-living/fragrance')]</value>
      <webElementGuid>5ec66e4d-a83a-434f-8264-0fa5395ba3c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/a</value>
      <webElementGuid>47d57545-54a4-4f55-861d-46a821cdab43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/home-living/fragrance' and (text() = 'Fragrance' or . = 'Fragrance')]</value>
      <webElementGuid>d3797b24-23d1-40f1-ac18-4ae4666451aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
