<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_r_1e3bc3_1_2_3</name>
   <tag></tag>
   <elementGuidId>0ce73732-243f-4c31-a273-4d761e718d62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(2) > td:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>88bad6c9-de95-4ecf-862e-d2b9158dd40c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>5723ebca-6611-46b1-9830-408414e22000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6eXNg8YIoGddBTalkTu8y_z8ozyj34pNq4ktFzDja0bAe3mtsZA68vl4CW8r2hoRZjZw_1BC_KoItHmS4veYCsjHUjI9Kg5kcaPVrYchhDtyl_oVECVWhXYmeVJ69QdeBu71TH5vFXGhEzuFCnfKgtWska8pdi2IRW4IrU5xrLqZhfZ3xyvTHkonR86dhhSWszOBJkcczDsgiL3PPM64SDjJ7cVg&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb</value>
      <webElementGuid>c21e3122-c2ab-4bd1-a0c9-f12b277b4903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>31e5af19-bda4-48a8-b458-3a004008f220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/9to9_OR/Page_Daftar akun baru/iframe_Talk with Nina_c-a0tct5fa41ty</value>
      <webElementGuid>6f7ec1fe-ee97-4d68-b7de-93b6323d34f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      <webElementGuid>8541a71b-0592-4529-8e10-cd9d185750cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6eXNg8YIoGddBTalkTu8y_z8ozyj34pNq4ktFzDja0bAe3mtsZA68vl4CW8r2hoRZjZw_1BC_KoItHmS4veYCsjHUjI9Kg5kcaPVrYchhDtyl_oVECVWhXYmeVJ69QdeBu71TH5vFXGhEzuFCnfKgtWska8pdi2IRW4IrU5xrLqZhfZ3xyvTHkonR86dhhSWszOBJkcczDsgiL3PPM64SDjJ7cVg&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb')])[4]</value>
      <webElementGuid>a48fb773-1e10-446a-82f3-c250dba0e40a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
      <webElementGuid>1ee7debe-9d1f-4ce6-ac9f-3ffd81103b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6eXNg8YIoGddBTalkTu8y_z8ozyj34pNq4ktFzDja0bAe3mtsZA68vl4CW8r2hoRZjZw_1BC_KoItHmS4veYCsjHUjI9Kg5kcaPVrYchhDtyl_oVECVWhXYmeVJ69QdeBu71TH5vFXGhEzuFCnfKgtWska8pdi2IRW4IrU5xrLqZhfZ3xyvTHkonR86dhhSWszOBJkcczDsgiL3PPM64SDjJ7cVg&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb']</value>
      <webElementGuid>12329b71-275d-4510-9f40-3ea2a2ff7b8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
