<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_r_1e3bc3</name>
   <tag></tag>
   <elementGuidId>a0bf654e-948f-4c4c-b759-ef5eabac7e53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>359c2b0b-9df0-4706-a5a2-4c4a2d973c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>e40dd8f8-bab8-4c6c-91a6-eb91e6fec69d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5Z0Szu4H6BiUTZTPuhvZsTVGa4yc2Z8Q0cf6eBZWdtchpDMAiWb30Nsyj8yGqACAnglog6P-qABFDkkL_oOO3lf5eGdHNs57iuA5MwNyyY8v10UOn-hK0UcKtzLVwNRxxnHHOKES2CT5uSaHXU74D-AbGxfq3UnNsLQOT7bBj_uqgms1t5rh1bR42LS5EXsYDEDUZLRiMNYlhsMyswX-enWxap9w&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb</value>
      <webElementGuid>da6d684f-a6e0-4199-9c8a-3d98a7aaa45e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>0e557db4-2d8f-4781-9be2-a9cf97de4e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/9to9_OR/Page_Daftar akun baru/iframe_Talk with Nina_c-a0tct5fa41ty</value>
      <webElementGuid>cdcbd954-5fb2-472f-bb37-d6293c1a560c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      <webElementGuid>0fe0b4e6-a574-4dca-aa0d-baec7b893ba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5Z0Szu4H6BiUTZTPuhvZsTVGa4yc2Z8Q0cf6eBZWdtchpDMAiWb30Nsyj8yGqACAnglog6P-qABFDkkL_oOO3lf5eGdHNs57iuA5MwNyyY8v10UOn-hK0UcKtzLVwNRxxnHHOKES2CT5uSaHXU74D-AbGxfq3UnNsLQOT7bBj_uqgms1t5rh1bR42LS5EXsYDEDUZLRiMNYlhsMyswX-enWxap9w&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb')])[8]</value>
      <webElementGuid>cc5e7935-aa09-4f61-99dd-93dcc4f42f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/div/img</value>
      <webElementGuid>82861c16-c38e-43a1-be5f-dde53ab1351b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5Z0Szu4H6BiUTZTPuhvZsTVGa4yc2Z8Q0cf6eBZWdtchpDMAiWb30Nsyj8yGqACAnglog6P-qABFDkkL_oOO3lf5eGdHNs57iuA5MwNyyY8v10UOn-hK0UcKtzLVwNRxxnHHOKES2CT5uSaHXU74D-AbGxfq3UnNsLQOT7bBj_uqgms1t5rh1bR42LS5EXsYDEDUZLRiMNYlhsMyswX-enWxap9w&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb']</value>
      <webElementGuid>82100cf9-fc16-464d-8c33-dd641c49e0ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
