<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_r_1e3bc3_1_2</name>
   <tag></tag>
   <elementGuidId>920dce58-1108-4933-8de1-b48b37008969</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>td:nth-child(3) >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f25fb869-4f1e-4e41-8e7a-548583beed04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>264f3f31-9b65-4c65-8207-9d982c532f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6eXNg8YIoGddBTalkTu8y_z8ozyj34pNq4ktFzDja0bAe3mtsZA68vl4CW8r2hoRZjZw_1BC_KoItHmS4veYCsjHUjI9Kg5kcaPVrYchhDtyl_oVECVWhXYmeVJ69QdeBu71TH5vFXGhEzuFCnfKgtWska8pdi2IRW4IrU5xrLqZhfZ3xyvTHkonR86dhhSWszOBJkcczDsgiL3PPM64SDjJ7cVg&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb</value>
      <webElementGuid>f3226b95-a7b8-4683-9741-91025fa6937a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>4af5794a-dc1e-47a2-b758-5a888ee6a6d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/9to9_OR/Page_Daftar akun baru/iframe_Talk with Nina_c-a0tct5fa41ty</value>
      <webElementGuid>a142210b-eb98-4783-90d5-cfb807c26e19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
      <webElementGuid>2409dee0-c729-4048-95e7-0edfd046f3a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6eXNg8YIoGddBTalkTu8y_z8ozyj34pNq4ktFzDja0bAe3mtsZA68vl4CW8r2hoRZjZw_1BC_KoItHmS4veYCsjHUjI9Kg5kcaPVrYchhDtyl_oVECVWhXYmeVJ69QdeBu71TH5vFXGhEzuFCnfKgtWska8pdi2IRW4IrU5xrLqZhfZ3xyvTHkonR86dhhSWszOBJkcczDsgiL3PPM64SDjJ7cVg&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb')])[2]</value>
      <webElementGuid>528b2526-4951-42f8-ad46-21a7ddd90b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/img</value>
      <webElementGuid>498e86e6-42d9-45e6-83de-863ca7d761ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6eXNg8YIoGddBTalkTu8y_z8ozyj34pNq4ktFzDja0bAe3mtsZA68vl4CW8r2hoRZjZw_1BC_KoItHmS4veYCsjHUjI9Kg5kcaPVrYchhDtyl_oVECVWhXYmeVJ69QdeBu71TH5vFXGhEzuFCnfKgtWska8pdi2IRW4IrU5xrLqZhfZ3xyvTHkonR86dhhSWszOBJkcczDsgiL3PPM64SDjJ7cVg&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb']</value>
      <webElementGuid>ce069458-e225-4297-a0f3-e7ac05cbb2d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
