<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>b346a360-5ce0-4b83-8dfe-3e5e86a3613c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.rc-image-tile-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.rc-imageselect-tile >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a93ae27b-a0f0-487d-bb53-21d4e37de129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>d6a5e148-99f7-40d1-b726-40395c51b4d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5Z0Szu4H6BiUTZTPuhvZsTVGa4yc2Z8Q0cf6eBZWdtchpDMAiWb30Nsyj8yGqACAnglog6P-qABFDkkL_oOO3lf5eGdHNs57iuA5MwNyyY8v10UOn-hK0UcKtzLVwNRxxnHHOKES2CT5uSaHXU74D-AbGxfq3UnNsLQOT7bBj_uqgms1t5rh1bR42LS5EXsYDEDUZLRiMNYlhsMyswX-enWxap9w&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb</value>
      <webElementGuid>b12639a6-0a78-4bc9-aac3-ef42d191e9e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>fe0f468e-6b3b-44c1-a95d-f49eeb2b91c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/9to9_OR/Page_Daftar akun baru/iframe_Talk with Nina_c-a0tct5fa41ty</value>
      <webElementGuid>e5025b22-8646-40ce-8c6a-60fbdee8822f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      <webElementGuid>beb33f85-5254-4901-abdc-2f83b9dae878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5Z0Szu4H6BiUTZTPuhvZsTVGa4yc2Z8Q0cf6eBZWdtchpDMAiWb30Nsyj8yGqACAnglog6P-qABFDkkL_oOO3lf5eGdHNs57iuA5MwNyyY8v10UOn-hK0UcKtzLVwNRxxnHHOKES2CT5uSaHXU74D-AbGxfq3UnNsLQOT7bBj_uqgms1t5rh1bR42LS5EXsYDEDUZLRiMNYlhsMyswX-enWxap9w&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb')]</value>
      <webElementGuid>5f626ec8-fc1f-46e0-b10c-5aa0767b40ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>563a3a34-7df1-4765-ab8d-1c94370c57b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5Z0Szu4H6BiUTZTPuhvZsTVGa4yc2Z8Q0cf6eBZWdtchpDMAiWb30Nsyj8yGqACAnglog6P-qABFDkkL_oOO3lf5eGdHNs57iuA5MwNyyY8v10UOn-hK0UcKtzLVwNRxxnHHOKES2CT5uSaHXU74D-AbGxfq3UnNsLQOT7bBj_uqgms1t5rh1bR42LS5EXsYDEDUZLRiMNYlhsMyswX-enWxap9w&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb']</value>
      <webElementGuid>0866a6e4-c2b8-4c09-8443-69f0ca7d8310</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
