<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_r_1e3bc3_1</name>
   <tag></tag>
   <elementGuidId>034016c3-5ccb-4442-badd-0f7d1c88dcfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.rc-image-tile-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.rc-imageselect-tile >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5d6da040-c67f-4088-b273-02364b0c7e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>1df1bfe7-788d-4a44-a622-75c40c5a07ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6eXNg8YIoGddBTalkTu8y_z8ozyj34pNq4ktFzDja0bAe3mtsZA68vl4CW8r2hoRZjZw_1BC_KoItHmS4veYCsjHUjI9Kg5kcaPVrYchhDtyl_oVECVWhXYmeVJ69QdeBu71TH5vFXGhEzuFCnfKgtWska8pdi2IRW4IrU5xrLqZhfZ3xyvTHkonR86dhhSWszOBJkcczDsgiL3PPM64SDjJ7cVg&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb</value>
      <webElementGuid>fdd3662d-6391-4158-9149-6a1a6e3941e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>6dacf7ed-b172-4a73-aaea-889d2653a1ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/9to9_OR/Page_Daftar akun baru/iframe_Talk with Nina_c-a0tct5fa41ty</value>
      <webElementGuid>4a8177e6-fefe-48ad-9428-5eca72499954</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      <webElementGuid>7f160622-836b-466c-8a70-4c53094ad952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6eXNg8YIoGddBTalkTu8y_z8ozyj34pNq4ktFzDja0bAe3mtsZA68vl4CW8r2hoRZjZw_1BC_KoItHmS4veYCsjHUjI9Kg5kcaPVrYchhDtyl_oVECVWhXYmeVJ69QdeBu71TH5vFXGhEzuFCnfKgtWska8pdi2IRW4IrU5xrLqZhfZ3xyvTHkonR86dhhSWszOBJkcczDsgiL3PPM64SDjJ7cVg&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb')]</value>
      <webElementGuid>7d1fcc4a-bd18-463f-9ff2-42fed01a0a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>0cf8c7c3-7e76-4923-aadd-7ec180e09627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6eXNg8YIoGddBTalkTu8y_z8ozyj34pNq4ktFzDja0bAe3mtsZA68vl4CW8r2hoRZjZw_1BC_KoItHmS4veYCsjHUjI9Kg5kcaPVrYchhDtyl_oVECVWhXYmeVJ69QdeBu71TH5vFXGhEzuFCnfKgtWska8pdi2IRW4IrU5xrLqZhfZ3xyvTHkonR86dhhSWszOBJkcczDsgiL3PPM64SDjJ7cVg&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb']</value>
      <webElementGuid>02a44d72-057b-46b7-aa1e-5a9997e8e3a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
