<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Validate</name>
   <tag></tag>
   <elementGuidId>b33f6361-de4d-4f2f-818e-8d5fd3bb3452</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.MuiTypography-root.jss207.jss210.jss216.jss221.jss202.jss211.MuiTypography-caption.MuiTypography-alignLeft</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div/div/form/div[8]/div/button/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Validate&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>30b80fce-366e-486d-9ad1-8dda6d7dafaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root jss207 jss210 jss216 jss221 jss202 jss211 MuiTypography-caption MuiTypography-alignLeft</value>
      <webElementGuid>cdd1366d-4ad5-4285-84d4-24b141970dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Validate</value>
      <webElementGuid>0d001b45-d342-4a6d-b344-87e82c715379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;jss296 row&quot;]/div[@class=&quot;col-lg-6 col-md-6 col-sm-12 col-xs-12&quot;]/div[@class=&quot;jss297&quot;]/form[1]/div[@class=&quot;jss268 jss270&quot;]/div[@class=&quot;jss271&quot;]/button[@class=&quot;MuiButtonBase-root MuiButton-root MuiButton-contained jss300 MuiButton-containedPrimary&quot;]/span[@class=&quot;MuiButton-label&quot;]/span[@class=&quot;MuiTypography-root jss207 jss210 jss216 jss221 jss202 jss211 MuiTypography-caption MuiTypography-alignLeft&quot;]</value>
      <webElementGuid>3c32e6af-c59e-47cb-ae80-e3eaf6405904</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/div/form/div[8]/div/button/span/span</value>
      <webElementGuid>76cdcac3-4408-4f96-b107-599b0d8acd40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[6]/following::span[2]</value>
      <webElementGuid>4e0654b6-7944-4a6e-ae72-eddb42193696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OTP'])[1]/following::span[3]</value>
      <webElementGuid>2bfb8f09-30fe-4891-9c84-94cd0c7aab67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::span[4]</value>
      <webElementGuid>6a048f82-c869-481c-bff4-1dd747e918ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[7]/preceding::span[6]</value>
      <webElementGuid>56986de9-9bac-41c9-9583-f34e23f20574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Validate']/parent::*</value>
      <webElementGuid>94182275-12c7-4913-913d-07119835def3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/button/span/span</value>
      <webElementGuid>83fdc6d6-3f0d-4e26-acf1-f32e67cbeb87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Validate' or . = 'Validate')]</value>
      <webElementGuid>52c7d1cf-a540-45d1-bcd9-649cb4dec56c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
