<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_TENTANG 9to9_jsx-2611454927 img loaded</name>
   <tag></tag>
   <elementGuidId>579ee3d1-66c0-4bcc-ba75-397f75d8fc83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.jsx-2611454927.img.loaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/main/div/div/div/div/div/a/div/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;9to9&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>77ced309-b9ae-42f9-b1ae-89e9a03d672f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-no-defer</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1b49b3ac-1991-4ce9-a0eb-72c38b3fb85a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://thumbor.sirclocdn.com/unsafe/48x48/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/logo/stores/1/9to9_June_Logo_90x90_RESIZE_1.png</value>
      <webElementGuid>d7705e5e-5417-48b9-8a7d-51278d2e20cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>9to9</value>
      <webElementGuid>515350c8-d2d4-480c-ae46-247f4580d847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>b57ec02e-8fba-4601-85f0-b2bdf786e5f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>6716517a-1ee6-45c7-a34f-72ef2bb29a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>9d850edf-8752-4737-98f7-82197e677779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-2611454927 img loaded</value>
      <webElementGuid>fde05494-8a0a-41e3-bbb1-7cb33a5d6de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/main[@class=&quot;jsx-2371353177 header-main-container&quot;]/div[@class=&quot;jsx-2371353177 header-main&quot;]/div[@class=&quot;jsx-2371353177 header-middle&quot;]/div[@class=&quot;jsx-2371353177 header-middle__left&quot;]/div[@class=&quot;jsx-2371353177 menu-category&quot;]/div[@class=&quot;jsx-2371353177 box header-middle__logo&quot;]/a[@class=&quot;jsx-2371353177&quot;]/div[1]/picture[@class=&quot;jsx-2611454927&quot;]/img[@class=&quot;jsx-2611454927 img loaded&quot;]</value>
      <webElementGuid>d94ec4b9-bcbd-4684-8430-668646fd3d61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/main/div/div/div/div/div/a/div/picture/img</value>
      <webElementGuid>e807acec-1e86-4fc8-8654-bdc2f42390ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='9to9']</value>
      <webElementGuid>7d0e5b59-bac5-4456-8e36-e3982e4b035e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/picture/img</value>
      <webElementGuid>e1bd7ef1-74f8-4983-8da6-b164799632c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://thumbor.sirclocdn.com/unsafe/48x48/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/logo/stores/1/9to9_June_Logo_90x90_RESIZE_1.png' and @alt = '9to9']</value>
      <webElementGuid>f8354e44-31c3-489c-8300-7e371ea48413</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
