<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1</name>
   <tag></tag>
   <elementGuidId>eabc6bbe-52d0-4ed0-b8ab-650ad647c847</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.MuiBadge-badge.jss837.MuiBadge-anchorOriginTopRightRectangle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/main/div/div/div[3]/div[2]/div/a/div/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;1&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>99075c38-c833-4742-b611-949f997887d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBadge-badge jss837 MuiBadge-anchorOriginTopRightRectangle</value>
      <webElementGuid>c0f1fd6f-67bb-4c35-aba5-fc353198b463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d5b1aa16-f47d-4a5f-b325-4cee40c5efd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/main[@class=&quot;jsx-2371353177 header-main-container&quot;]/div[@class=&quot;jsx-2371353177 header-main&quot;]/div[@class=&quot;jsx-2371353177 header-middle&quot;]/div[@class=&quot;jsx-2371353177 header-middle__right hidden-mobile&quot;]/div[@class=&quot;jsx-2371353177 header-middle__item hidden-mobile&quot;]/div[@class=&quot;jsx-2371353177 header-middle__icon&quot;]/a[@class=&quot;jsx-2371353177&quot;]/div[1]/span[@class=&quot;MuiBadge-root jss836&quot;]/span[@class=&quot;MuiBadge-badge jss837 MuiBadge-anchorOriginTopRightRectangle&quot;]</value>
      <webElementGuid>164f51ae-e02e-42ec-b9ce-754fcb8802a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/main/div/div/div[3]/div[2]/div/a/div/span/span</value>
      <webElementGuid>c0be14fc-3f1b-415a-b1e5-27c39c69ac2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::span[2]</value>
      <webElementGuid>1a70f568-655f-4bbd-9cf7-7ee217b6bac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TENTANG 9to9'])[1]/following::span[10]</value>
      <webElementGuid>3930a76a-3dc2-4e07-9638-5f15b41740c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HI, GUEST'])[1]/preceding::span[1]</value>
      <webElementGuid>4dc85da0-adf0-481e-ad4e-87831c259a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fashion'])[1]/preceding::span[1]</value>
      <webElementGuid>6e59ea70-5d36-4b90-aa39-d603aaafa6ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1']/parent::*</value>
      <webElementGuid>1e62ca59-96e0-4d58-88d8-bc07efbf03c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/span</value>
      <webElementGuid>a21f2c49-de3c-43ca-af99-08a064ce21ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '1' or . = '1')]</value>
      <webElementGuid>6344bd10-fb55-4afd-bfc0-b52832502036</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
