<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__a-5obdhieyxg1h</name>
   <tag></tag>
   <elementGuidId>966bb92d-85f4-49f3-8aa4-207329d82be2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-5obdhieyxg1h&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-5obdhieyxg1h']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;a-5obdhieyxg1h&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ab11dc40-4dfa-4fac-bd45-da3b606dcda2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>8d59287d-f213-40a6-9e2a-ae1005f0d5c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>165dba32-34fc-4696-8342-318438dd132e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>e059df45-91d0-42f5-8264-2b4488e276e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>ab6a9876-9c1c-4864-afcb-7fac9ed82107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-5obdhieyxg1h</value>
      <webElementGuid>64b8b47a-501b-4c0a-add8-11a40602c0a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2e3cdd2e-88e4-455e-ac75-a804e3e70cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>2416133d-1d6f-4d5e-a636-8cb9ae6db0fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>d32d5cc2-66eb-4419-a981-fe6850308d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb&amp;co=aHR0cHM6Ly85dG85LmNvLmlkOjQ0Mw..&amp;hl=en&amp;type=image&amp;v=hbAq-YhJxOnlU-7cpgBoAJHb&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=od6r3fuczvgv</value>
      <webElementGuid>3d7e916d-ba79-4946-9a18-944ff527be94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;jss342 row&quot;]/div[@class=&quot;col-md-6 col-xs-12&quot;]/div[@class=&quot;jss343&quot;]/form[1]/div[@class=&quot;jss349&quot;]/div[1]/div[1]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>890b06c9-0270-4dc9-b598-e91f93b7d1cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-5obdhieyxg1h']</value>
      <webElementGuid>ea8a7196-f64b-4b20-bda1-f6387e6f4342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/div/form/div[3]/div/div/div/div/iframe</value>
      <webElementGuid>35a871ca-106f-4b51-9f8d-b7f34d43a3fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>bb2525a8-9e2b-4c1e-9e72-b772276d2383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-5obdhieyxg1h' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb&amp;co=aHR0cHM6Ly85dG85LmNvLmlkOjQ0Mw..&amp;hl=en&amp;type=image&amp;v=hbAq-YhJxOnlU-7cpgBoAJHb&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=od6r3fuczvgv']</value>
      <webElementGuid>68eb3eae-121e-43a1-a615-6a7f2e6051f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
