<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22_23</name>
   <tag></tag>
   <elementGuidId>5737ca1a-3efe-41ad-8f58-78c27e783ca2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.rc-image-tile-44</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.rc-imageselect-tile >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0a95bd94-5ba9-4bc4-82b3-3e2c180bae6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>4000b2ec-5520-4033-8ac7-ecc2f5b7b022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6OCU_I-Sxll0QfcI3k0WF1jDnn-vANOqZXyfIbVR4p2ZrB2kCgUDaTzWNHoO1dfJBCc18tcIrPH448xmyxGhl0gVAEmZBYaX1vJOCr_fBvbKySnOVTNd3ba_5s21oVkdWrvuXgSI5m99h10ZT0c8R7c0No7_9GHD72DJJuwbAUNPqslWdmdOm44d0GKnPdJ9q22TVW&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb&amp;id=2</value>
      <webElementGuid>af41bf47-8809-489e-b05a-4d9b53ecbb61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>b167f49d-c391-4193-83c0-73a38fe58adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/9to9_OR/Page_Lupa password/iframe_Talk with Nina_c-5obdhieyxg1h</value>
      <webElementGuid>d0d279f5-9d67-4cfc-bbbd-c5e5273b05ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      <webElementGuid>acda5c7b-aac4-4684-80e8-b7d63f0b2b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6OCU_I-Sxll0QfcI3k0WF1jDnn-vANOqZXyfIbVR4p2ZrB2kCgUDaTzWNHoO1dfJBCc18tcIrPH448xmyxGhl0gVAEmZBYaX1vJOCr_fBvbKySnOVTNd3ba_5s21oVkdWrvuXgSI5m99h10ZT0c8R7c0No7_9GHD72DJJuwbAUNPqslWdmdOm44d0GKnPdJ9q22TVW&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb&amp;id=2')]</value>
      <webElementGuid>a6a5c597-9fa8-42b3-abbb-bf3ec6266db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>2af57466-1a18-4079-bf9f-70c155aa8c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6OCU_I-Sxll0QfcI3k0WF1jDnn-vANOqZXyfIbVR4p2ZrB2kCgUDaTzWNHoO1dfJBCc18tcIrPH448xmyxGhl0gVAEmZBYaX1vJOCr_fBvbKySnOVTNd3ba_5s21oVkdWrvuXgSI5m99h10ZT0c8R7c0No7_9GHD72DJJuwbAUNPqslWdmdOm44d0GKnPdJ9q22TVW&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb&amp;id=2']</value>
      <webElementGuid>9ed8de60-1b5c-4200-8589-9f35bfc13880</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
