<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17</name>
   <tag></tag>
   <elementGuidId>a08411f8-f477-4553-b1d0-a7debceaedb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a2f2493e-8a99-4fae-9780-4c0d0ae6fb89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>05acbda4-657b-424a-b650-43ec124c9c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6OCU_I-Sxll0QfcI3k0WF1jDnn-vANOqZXyfIbVR4p2ZrB2kCgUDaTzWNHoO1dfJBCc18tcIrPH448xmyxGhl0gVAEmZBYaX1vJOCr_fBvbKySnOVTNd3ba_5s21oVkdWrvuXgSI5m99h10ZT0c8R7c0No7_9GHD72DJJuwbAUNPqslWdmdOm44d0GKnPdJ9q22TVW&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb</value>
      <webElementGuid>e5b31762-53d1-47e6-9990-2e545bec2ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>bdf16564-a43d-49f9-85b0-edfe263e0c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/9to9_OR/Page_Lupa password/iframe_Talk with Nina_c-5obdhieyxg1h</value>
      <webElementGuid>61d2c9d2-7d1e-43a0-8cf7-fbae73ad85d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      <webElementGuid>730f9d72-c91d-4708-8bcc-4fc565b6ccf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6OCU_I-Sxll0QfcI3k0WF1jDnn-vANOqZXyfIbVR4p2ZrB2kCgUDaTzWNHoO1dfJBCc18tcIrPH448xmyxGhl0gVAEmZBYaX1vJOCr_fBvbKySnOVTNd3ba_5s21oVkdWrvuXgSI5m99h10ZT0c8R7c0No7_9GHD72DJJuwbAUNPqslWdmdOm44d0GKnPdJ9q22TVW&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb')])[11]</value>
      <webElementGuid>77dafdd8-39d7-4e74-9245-12aacfdcf682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/div/img</value>
      <webElementGuid>79902c9b-26d2-40c4-891d-4d72c18828fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6OCU_I-Sxll0QfcI3k0WF1jDnn-vANOqZXyfIbVR4p2ZrB2kCgUDaTzWNHoO1dfJBCc18tcIrPH448xmyxGhl0gVAEmZBYaX1vJOCr_fBvbKySnOVTNd3ba_5s21oVkdWrvuXgSI5m99h10ZT0c8R7c0No7_9GHD72DJJuwbAUNPqslWdmdOm44d0GKnPdJ9q22TVW&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb']</value>
      <webElementGuid>30ac5de4-1a69-4183-93d0-e73bb0f66d0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
