<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12</name>
   <tag></tag>
   <elementGuidId>bd8a5357-ba9e-41f2-bb6c-f3975b6928b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(2) > td:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4a763b79-1b2e-42a5-a484-d0730ab3d846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>3aa86de3-3afd-4777-b151-693fb7643e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7wnhTwrIcxzA4pP21C8OugkatPtt1e8FGxo1o9b3Ikeze7coedY8Ux1rrTcBStapFusyCY7AN5X1Jxy-jQHx0dXfjcTBre694ECB_L_LhkK0Hq-TZe0kz7PNgmz3UeC7anwyaoxrMhpEK3UPD2YU-jypnrIftS3RSOnHybmBWNWqSisNqwuMzvYZIubuD1WgeIsIrg&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb&amp;id=2</value>
      <webElementGuid>737b2113-e73f-473a-bf36-9e256a9e55af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>47130710-c1d6-491b-9384-8c1eea3a6a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/9to9_OR/Page_Lupa password/iframe_Talk with Nina_c-5obdhieyxg1h</value>
      <webElementGuid>2498d3b9-3017-42ae-a2db-5677b36b1bed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
      <webElementGuid>897a75d4-1196-4fc5-ba80-9720b44e5726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7wnhTwrIcxzA4pP21C8OugkatPtt1e8FGxo1o9b3Ikeze7coedY8Ux1rrTcBStapFusyCY7AN5X1Jxy-jQHx0dXfjcTBre694ECB_L_LhkK0Hq-TZe0kz7PNgmz3UeC7anwyaoxrMhpEK3UPD2YU-jypnrIftS3RSOnHybmBWNWqSisNqwuMzvYZIubuD1WgeIsIrg&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb&amp;id=2')])[7]</value>
      <webElementGuid>e01f3551-5ab7-42d0-8478-dc428d592143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div/div/img</value>
      <webElementGuid>d19c03a2-67f9-4049-b912-b7dd6ba2cad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7wnhTwrIcxzA4pP21C8OugkatPtt1e8FGxo1o9b3Ikeze7coedY8Ux1rrTcBStapFusyCY7AN5X1Jxy-jQHx0dXfjcTBre694ECB_L_LhkK0Hq-TZe0kz7PNgmz3UeC7anwyaoxrMhpEK3UPD2YU-jypnrIftS3RSOnHybmBWNWqSisNqwuMzvYZIubuD1WgeIsIrg&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb&amp;id=2']</value>
      <webElementGuid>9cb9672a-abe9-4161-8c9e-ce7fbe35d21f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
