<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14</name>
   <tag></tag>
   <elementGuidId>2f3b22c4-21d5-4616-b98d-7860eb22a80d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b961a90b-1040-4612-938d-18898bc27909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>35122fe7-7879-4b5c-9f1a-ece5aec3261f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7wnhTwrIcxzA4pP21C8OugkatPtt1e8FGxo1o9b3Ikeze7coedY8Ux1rrTcBStapFusyCY7AN5X1Jxy-jQHx0dXfjcTBre694ECB_L_LhkK0Hq-TZe0kz7PNgmz3UeC7anwyaoxrMhpEK3UPD2YU-jypnrIftS3RSOnHybmBWNWqSisNqwuMzvYZIubuD1WgeIsIrg&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb&amp;id=2</value>
      <webElementGuid>9d593773-5d7e-4500-b01e-4fdfd35e47a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>59ea028c-f2f5-4378-9e5d-db197b84e054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/9to9_OR/Page_Lupa password/iframe_Talk with Nina_c-5obdhieyxg1h</value>
      <webElementGuid>875f28df-72eb-4d70-9a2b-2190f0d0e7d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      <webElementGuid>0a06824c-f3be-4253-85fa-f7b6f8d3a716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7wnhTwrIcxzA4pP21C8OugkatPtt1e8FGxo1o9b3Ikeze7coedY8Ux1rrTcBStapFusyCY7AN5X1Jxy-jQHx0dXfjcTBre694ECB_L_LhkK0Hq-TZe0kz7PNgmz3UeC7anwyaoxrMhpEK3UPD2YU-jypnrIftS3RSOnHybmBWNWqSisNqwuMzvYZIubuD1WgeIsIrg&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb&amp;id=2')])[10]</value>
      <webElementGuid>522a8e6c-4f62-4dde-9ceb-b31c80aa1479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/div/img</value>
      <webElementGuid>25c63551-6521-425e-bd17-e92742e51203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7wnhTwrIcxzA4pP21C8OugkatPtt1e8FGxo1o9b3Ikeze7coedY8Ux1rrTcBStapFusyCY7AN5X1Jxy-jQHx0dXfjcTBre694ECB_L_LhkK0Hq-TZe0kz7PNgmz3UeC7anwyaoxrMhpEK3UPD2YU-jypnrIftS3RSOnHybmBWNWqSisNqwuMzvYZIubuD1WgeIsIrg&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb&amp;id=2']</value>
      <webElementGuid>0294edef-a767-4bd9-b62e-9355c3e4eb25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
