<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9</name>
   <tag></tag>
   <elementGuidId>aa2e7077-95f3-49bb-b2d1-6de85f4e5643</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>td:nth-child(2) >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1e760d38-0442-4230-8fb0-b207a70919ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>e74707ab-1bcf-4e60-8d81-4776fb0bdabd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7wnhTwrIcxzA4pP21C8OugkatPtt1e8FGxo1o9b3Ikeze7coedY8Ux1rrTcBStapFusyCY7AN5X1Jxy-jQHx0dXfjcTBre694ECB_L_LhkK0Hq-TZe0kz7PNgmz3UeC7anwyaoxrMhpEK3UPD2YU-jypnrIftS3RSOnHybmBWNWqSisNqwuMzvYZIubuD1WgeIsIrg&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb</value>
      <webElementGuid>ca476a82-b8d2-4853-8f3a-0e18aa999902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>2fac4dca-ac3a-418c-a653-eb0e12b4708c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/9to9_OR/Page_Lupa password/iframe_Talk with Nina_c-5obdhieyxg1h</value>
      <webElementGuid>c6c9e04c-70f8-427d-990a-60c5865e61e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
      <webElementGuid>59a66bac-10fe-4226-88d5-52a0d45749d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7wnhTwrIcxzA4pP21C8OugkatPtt1e8FGxo1o9b3Ikeze7coedY8Ux1rrTcBStapFusyCY7AN5X1Jxy-jQHx0dXfjcTBre694ECB_L_LhkK0Hq-TZe0kz7PNgmz3UeC7anwyaoxrMhpEK3UPD2YU-jypnrIftS3RSOnHybmBWNWqSisNqwuMzvYZIubuD1WgeIsIrg&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb')])[2]</value>
      <webElementGuid>222cd1e3-7f38-425f-8320-ebf32681a79c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/img</value>
      <webElementGuid>e5a31e74-9574-46c7-bb2a-6f55c212dd86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7wnhTwrIcxzA4pP21C8OugkatPtt1e8FGxo1o9b3Ikeze7coedY8Ux1rrTcBStapFusyCY7AN5X1Jxy-jQHx0dXfjcTBre694ECB_L_LhkK0Hq-TZe0kz7PNgmz3UeC7anwyaoxrMhpEK3UPD2YU-jypnrIftS3RSOnHybmBWNWqSisNqwuMzvYZIubuD1WgeIsIrg&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb']</value>
      <webElementGuid>99ae0fa7-88b2-4f82-bf67-d896e3c2e561</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
