<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>68600a0d-1bc4-4641-8214-2a5b9801ba96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(2) > td:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e6674dc6-5a45-44a3-9926-239b1a3a0be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>11d97396-fa53-452a-b633-9dcdc8f2f70d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7wnhTwrIcxzA4pP21C8OugkatPtt1e8FGxo1o9b3Ikeze7coedY8Ux1rrTcBStapFusyCY7AN5X1Jxy-jQHx0dXfjcTBre694ECB_L_LhkK0Hq-TZe0kz7PNgmz3UeC7anwyaoxrMhpEK3UPD2YU-jypnrIftS3RSOnHybmBWNWqSisNqwuMzvYZIubuD1WgeIsIrg&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb</value>
      <webElementGuid>116f7cc6-4df4-4085-9a9e-076833beae47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>b830e9f0-c269-41f6-8f4f-ed2d4144a599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/9to9_OR/Page_Lupa password/iframe_Talk with Nina_c-5obdhieyxg1h</value>
      <webElementGuid>005c123f-3c26-4513-9f1a-3e670399c50c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
      <webElementGuid>ba516818-42d4-4e66-a25a-9c08c628ed41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7wnhTwrIcxzA4pP21C8OugkatPtt1e8FGxo1o9b3Ikeze7coedY8Ux1rrTcBStapFusyCY7AN5X1Jxy-jQHx0dXfjcTBre694ECB_L_LhkK0Hq-TZe0kz7PNgmz3UeC7anwyaoxrMhpEK3UPD2YU-jypnrIftS3RSOnHybmBWNWqSisNqwuMzvYZIubuD1WgeIsIrg&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb')])[7]</value>
      <webElementGuid>bad260a7-4de7-403f-ba9c-ecb59f8fcc27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div/div/img</value>
      <webElementGuid>1ec006eb-21d4-4860-a68e-899722ef8fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7wnhTwrIcxzA4pP21C8OugkatPtt1e8FGxo1o9b3Ikeze7coedY8Ux1rrTcBStapFusyCY7AN5X1Jxy-jQHx0dXfjcTBre694ECB_L_LhkK0Hq-TZe0kz7PNgmz3UeC7anwyaoxrMhpEK3UPD2YU-jypnrIftS3RSOnHybmBWNWqSisNqwuMzvYZIubuD1WgeIsIrg&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb']</value>
      <webElementGuid>cbbcc7bf-04a2-4001-ab44-eeb756ad2dc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
