<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20</name>
   <tag></tag>
   <elementGuidId>603ba868-da33-4bed-ae20-98787815a778</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[4]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(4)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4e0f9497-079c-43ae-8424-76647580be39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>74d93313-004d-4546-8607-a0d68d32af35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6OCU_I-Sxll0QfcI3k0WF1jDnn-vANOqZXyfIbVR4p2ZrB2kCgUDaTzWNHoO1dfJBCc18tcIrPH448xmyxGhl0gVAEmZBYaX1vJOCr_fBvbKySnOVTNd3ba_5s21oVkdWrvuXgSI5m99h10ZT0c8R7c0No7_9GHD72DJJuwbAUNPqslWdmdOm44d0GKnPdJ9q22TVW&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb</value>
      <webElementGuid>d7316d8c-8065-4702-84a0-df24c472f5f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>8de5f1e2-dfbe-46da-bb14-85cd89719663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/9to9_OR/Page_Lupa password/iframe_Talk with Nina_c-5obdhieyxg1h</value>
      <webElementGuid>d34bdc51-101e-4c83-bd2f-c6e378f713e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[4]/div/div/img</value>
      <webElementGuid>f3969166-4ab3-41ce-be3d-517a1bfa3d51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6OCU_I-Sxll0QfcI3k0WF1jDnn-vANOqZXyfIbVR4p2ZrB2kCgUDaTzWNHoO1dfJBCc18tcIrPH448xmyxGhl0gVAEmZBYaX1vJOCr_fBvbKySnOVTNd3ba_5s21oVkdWrvuXgSI5m99h10ZT0c8R7c0No7_9GHD72DJJuwbAUNPqslWdmdOm44d0GKnPdJ9q22TVW&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb')])[12]</value>
      <webElementGuid>d512445e-1a8b-4b92-adf5-f66dd38d5be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/div/div/img</value>
      <webElementGuid>08f21b88-54f6-4bcc-b0cb-0c7d55abe574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6OCU_I-Sxll0QfcI3k0WF1jDnn-vANOqZXyfIbVR4p2ZrB2kCgUDaTzWNHoO1dfJBCc18tcIrPH448xmyxGhl0gVAEmZBYaX1vJOCr_fBvbKySnOVTNd3ba_5s21oVkdWrvuXgSI5m99h10ZT0c8R7c0No7_9GHD72DJJuwbAUNPqslWdmdOm44d0GKnPdJ9q22TVW&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb']</value>
      <webElementGuid>a157198b-7b09-4a38-af73-73cdd80fbe71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
