<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19</name>
   <tag></tag>
   <elementGuidId>c4d0fb97-8d2f-45ab-a2a9-a843d80ed163</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[4]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(2) > td:nth-child(4)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4b5f9c8f-203d-4465-ba90-6d003c8226af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>72a3b953-a3af-4e3a-a20f-e3033d2b2b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6OCU_I-Sxll0QfcI3k0WF1jDnn-vANOqZXyfIbVR4p2ZrB2kCgUDaTzWNHoO1dfJBCc18tcIrPH448xmyxGhl0gVAEmZBYaX1vJOCr_fBvbKySnOVTNd3ba_5s21oVkdWrvuXgSI5m99h10ZT0c8R7c0No7_9GHD72DJJuwbAUNPqslWdmdOm44d0GKnPdJ9q22TVW&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb</value>
      <webElementGuid>0d4763bc-8187-4c4a-8170-797f7437612c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>46b0fd9a-65eb-46f1-a1fc-8654baae2c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/9to9_OR/Page_Lupa password/iframe_Talk with Nina_c-5obdhieyxg1h</value>
      <webElementGuid>391ef2a2-2ffc-4e10-9c97-ee8558d89838</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[4]/div/div/img</value>
      <webElementGuid>8a7b71f9-4fe4-42d9-86fa-a2d2183ea315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6OCU_I-Sxll0QfcI3k0WF1jDnn-vANOqZXyfIbVR4p2ZrB2kCgUDaTzWNHoO1dfJBCc18tcIrPH448xmyxGhl0gVAEmZBYaX1vJOCr_fBvbKySnOVTNd3ba_5s21oVkdWrvuXgSI5m99h10ZT0c8R7c0No7_9GHD72DJJuwbAUNPqslWdmdOm44d0GKnPdJ9q22TVW&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb')])[8]</value>
      <webElementGuid>149544ed-1a30-4279-8af4-1e0052b1b5f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/div/div/img</value>
      <webElementGuid>487a2a80-f550-4725-9350-74287b22ad18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6OCU_I-Sxll0QfcI3k0WF1jDnn-vANOqZXyfIbVR4p2ZrB2kCgUDaTzWNHoO1dfJBCc18tcIrPH448xmyxGhl0gVAEmZBYaX1vJOCr_fBvbKySnOVTNd3ba_5s21oVkdWrvuXgSI5m99h10ZT0c8R7c0No7_9GHD72DJJuwbAUNPqslWdmdOm44d0GKnPdJ9q22TVW&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb']</value>
      <webElementGuid>14536d13-c655-4247-a20d-031def72825b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
