<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7</name>
   <tag></tag>
   <elementGuidId>520c6354-22a1-4a02-b15e-7c214936cb0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(2) > td:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a831e242-b5b0-4c14-90e7-2261517c2a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>19f03978-0499-45f8-8897-3311f0f9a373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7wnhTwrIcxzA4pP21C8OugkatPtt1e8FGxo1o9b3Ikeze7coedY8Ux1rrTcBStapFusyCY7AN5X1Jxy-jQHx0dXfjcTBre694ECB_L_LhkK0Hq-TZe0kz7PNgmz3UeC7anwyaoxrMhpEK3UPD2YU-jypnrIftS3RSOnHybmBWNWqSisNqwuMzvYZIubuD1WgeIsIrg&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb</value>
      <webElementGuid>7aeaa5d2-77b4-414b-bdc5-85149a988710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>f0243929-f2d7-4e42-b1b3-d19ed6a87e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/9to9_OR/Page_Lupa password/iframe_Talk with Nina_c-5obdhieyxg1h</value>
      <webElementGuid>8d5736cf-d669-49cd-9859-b1f5428da814</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      <webElementGuid>77daeea0-35b4-44c8-996d-fcdff8d379b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7wnhTwrIcxzA4pP21C8OugkatPtt1e8FGxo1o9b3Ikeze7coedY8Ux1rrTcBStapFusyCY7AN5X1Jxy-jQHx0dXfjcTBre694ECB_L_LhkK0Hq-TZe0kz7PNgmz3UeC7anwyaoxrMhpEK3UPD2YU-jypnrIftS3RSOnHybmBWNWqSisNqwuMzvYZIubuD1WgeIsIrg&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb')])[6]</value>
      <webElementGuid>a12edb98-1b71-41db-99af-bd55ffb4dbb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
      <webElementGuid>2d7d920e-9fbf-4980-b318-f4473f2917bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7wnhTwrIcxzA4pP21C8OugkatPtt1e8FGxo1o9b3Ikeze7coedY8Ux1rrTcBStapFusyCY7AN5X1Jxy-jQHx0dXfjcTBre694ECB_L_LhkK0Hq-TZe0kz7PNgmz3UeC7anwyaoxrMhpEK3UPD2YU-jypnrIftS3RSOnHybmBWNWqSisNqwuMzvYZIubuD1WgeIsIrg&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb']</value>
      <webElementGuid>b67a06fa-28d9-40bc-b8a3-12c483452943</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
