<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22</name>
   <tag></tag>
   <elementGuidId>98f5a733-bc47-4494-882c-ab7917d52e66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(4) > td:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>455cd5f4-60ce-45b0-b519-e3e5686134f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>fd4c18fe-e0ed-4719-b57d-841b4b4b5709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6OCU_I-Sxll0QfcI3k0WF1jDnn-vANOqZXyfIbVR4p2ZrB2kCgUDaTzWNHoO1dfJBCc18tcIrPH448xmyxGhl0gVAEmZBYaX1vJOCr_fBvbKySnOVTNd3ba_5s21oVkdWrvuXgSI5m99h10ZT0c8R7c0No7_9GHD72DJJuwbAUNPqslWdmdOm44d0GKnPdJ9q22TVW&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb</value>
      <webElementGuid>3495f3c3-e90d-484d-b138-0217fc28350e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[4]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>b6ae2491-90f3-471a-91da-99e42eed6e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/9to9_OR/Page_Lupa password/iframe_Talk with Nina_c-5obdhieyxg1h</value>
      <webElementGuid>b3531fdc-1090-417a-90df-0f1c5b0bc444</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td[3]/div/div/img</value>
      <webElementGuid>6122ebce-3843-413a-af73-9b3e28f3770f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6OCU_I-Sxll0QfcI3k0WF1jDnn-vANOqZXyfIbVR4p2ZrB2kCgUDaTzWNHoO1dfJBCc18tcIrPH448xmyxGhl0gVAEmZBYaX1vJOCr_fBvbKySnOVTNd3ba_5s21oVkdWrvuXgSI5m99h10ZT0c8R7c0No7_9GHD72DJJuwbAUNPqslWdmdOm44d0GKnPdJ9q22TVW&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb')])[15]</value>
      <webElementGuid>4ebceff6-45a8-4542-b0d0-ebe7ad745350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[3]/div/div/img</value>
      <webElementGuid>a441d8e3-2d21-42df-b04b-4af2fd57bdb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6OCU_I-Sxll0QfcI3k0WF1jDnn-vANOqZXyfIbVR4p2ZrB2kCgUDaTzWNHoO1dfJBCc18tcIrPH448xmyxGhl0gVAEmZBYaX1vJOCr_fBvbKySnOVTNd3ba_5s21oVkdWrvuXgSI5m99h10ZT0c8R7c0No7_9GHD72DJJuwbAUNPqslWdmdOm44d0GKnPdJ9q22TVW&amp;k=6Le8_EAjAAAAAIMB5ygmCZ9VlM-vXhT9TOfSxprb']</value>
      <webElementGuid>0f0bbe39-77bb-45ca-b33e-d9bdbd14ebc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
