<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_keluar</name>
   <tag></tag>
   <elementGuidId>333bbb9f-f687-4df7-8f90-22f004ee4740</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.jsx-2371353177.header-middle__dropdown-list > a.jsx-2371353177</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/main/div/div/div[3]/div[4]/div[2]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;keluar&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4e1dc1a4-6820-491c-adf9-f61c1b2e0802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-2371353177</value>
      <webElementGuid>3c7f7c92-7918-4fc2-a2bb-292770517ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>keluar</value>
      <webElementGuid>27937995-b116-4e8f-a294-7ba53eba2d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/main[@class=&quot;jsx-2371353177 header-main-container&quot;]/div[@class=&quot;jsx-2371353177 header-main&quot;]/div[@class=&quot;jsx-2371353177 header-middle&quot;]/div[@class=&quot;jsx-2371353177 header-middle__right hidden-mobile&quot;]/div[@class=&quot;jsx-2371353177 header-middle__item hidden-mobile&quot;]/div[@class=&quot;jsx-2371353177 header-middle__account-name&quot;]/ul[@class=&quot;jsx-2371353177 header-middle__dropdown&quot;]/li[@class=&quot;jsx-2371353177 header-middle__dropdown-list&quot;]/a[@class=&quot;jsx-2371353177&quot;]</value>
      <webElementGuid>f873749a-aed3-4c11-9b8d-52430743d66e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/main/div/div/div[3]/div[4]/div[2]/ul/li/a</value>
      <webElementGuid>5cb1b711-bd11-4517-92ca-6b15e92ac2b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'keluar')]</value>
      <webElementGuid>03e5afc1-65af-4d6c-a40b-288dd8dfced1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HI, Muhammad'])[1]/following::a[1]</value>
      <webElementGuid>e651eb7d-4652-4712-9679-130d7091a07f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::a[5]</value>
      <webElementGuid>25bb6fc5-e0b2-4dc9-a60b-cdaa4b913fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fashion'])[1]/preceding::a[1]</value>
      <webElementGuid>1fd35336-a21f-4077-8ad7-1e4d2305f957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fashion Muslim'])[1]/preceding::a[2]</value>
      <webElementGuid>6ff43e57-989d-49a1-9b45-725b1fd5448e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='keluar']/parent::*</value>
      <webElementGuid>b944d580-b905-4bc0-b618-0940e54d5bc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a</value>
      <webElementGuid>6b90f665-26db-4175-9b54-ca4d5cbbeeba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'keluar' or . = 'keluar')]</value>
      <webElementGuid>17902994-6fb9-43bf-b662-37947dc2d1b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
