<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Koper</name>
   <tag></tag>
   <elementGuidId>9a45278b-397b-4003-aa3c-d5fa1c308a31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='nav']/li[2]/div/div/div[9]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Koper&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2819c0f9-40f1-405f-8048-8df2b67b4445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-1208550441 avenir-black</value>
      <webElementGuid>1f2c9940-af2d-4819-9996-c13dfc0d15ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/home-living/koper</value>
      <webElementGuid>114541f2-3fda-4a9f-aa2e-11fbe980a96a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Koper</value>
      <webElementGuid>01a06937-3c73-4d81-a158-5e66e8c89d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav&quot;)/li[@class=&quot;jsx-1208550441 nav-item&quot;]/div[@class=&quot;jsx-1208550441 mega-menu row&quot;]/div[@class=&quot;jsx-1208550441 nav-column row col-lg-12 col-md-12 col-sm-12&quot;]/div[@class=&quot;jsx-1208550441 list-item col-lg-3 col-md-4 col-sm-6&quot;]/a[@class=&quot;jsx-1208550441 avenir-black&quot;]</value>
      <webElementGuid>5d4d5385-1c77-4878-89f1-3ad1ee36c182</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='nav']/li[2]/div/div/div[9]/a</value>
      <webElementGuid>d33ceab2-a10d-407c-a767-ba2e56e78640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Koper')]</value>
      <webElementGuid>e93c1b6b-87c5-4013-b7cd-9d40b602e811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fragrance'])[1]/following::a[1]</value>
      <webElementGuid>8495a1bd-36e5-4984-adfe-7d894b64d3d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cutleries'])[1]/following::a[2]</value>
      <webElementGuid>5cfc68dc-6a73-407b-8aac-6c5e6cdeb824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Health &amp; Beauty'])[1]/preceding::a[1]</value>
      <webElementGuid>4f56cfff-58b3-4d84-9c15-d1982d554cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beauty'])[1]/preceding::a[2]</value>
      <webElementGuid>187245b6-809e-49ac-b70e-35ee3cd7b6b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Koper']/parent::*</value>
      <webElementGuid>d829d6af-b310-4145-af9d-3c977c82e359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/home-living/koper')]</value>
      <webElementGuid>bbc5d2a9-b0d1-418a-a663-7695bd1aadaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/a</value>
      <webElementGuid>9658cfbe-a275-4c67-b17b-a55ba7be793c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/home-living/koper' and (text() = 'Koper' or . = 'Koper')]</value>
      <webElementGuid>02dc0752-0eee-4907-84d6-72a72fef4050</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
