<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_TENTANG 9to9_jsx-2611454927 img loaded</name>
   <tag></tag>
   <elementGuidId>52b28abb-6cd2-4467-8623-350c41825e31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.jsx-2611454927.img.loaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/main/div/div/div/div/div/a/div/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;9to9&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d90eb62a-7272-4523-ab4f-6d334d8d7bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-no-defer</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>735f7db6-1886-4cde-b2f0-c253297e1464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://thumbor.sirclocdn.com/unsafe/48x48/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/logo/stores/1/9to9_June_Logo_90x90_RESIZE_1.png</value>
      <webElementGuid>b7cba88d-90c6-4ffb-8c67-05d256e804d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>9to9</value>
      <webElementGuid>f644f928-7987-4d86-89f6-a7d0fcfd1cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>8a3dc825-6982-43ff-b6ca-9de897c7cb50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>508cbb9c-a1bb-482c-aef4-f0475933113b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>79c725c3-a7d9-49f9-85e9-07dce2bd49bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-2611454927 img loaded</value>
      <webElementGuid>9729c20e-c2d9-421f-ab9c-72fbc6e90f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/main[@class=&quot;jsx-2371353177 header-main-container&quot;]/div[@class=&quot;jsx-2371353177 header-main&quot;]/div[@class=&quot;jsx-2371353177 header-middle&quot;]/div[@class=&quot;jsx-2371353177 header-middle__left&quot;]/div[@class=&quot;jsx-2371353177 menu-category&quot;]/div[@class=&quot;jsx-2371353177 box header-middle__logo&quot;]/a[@class=&quot;jsx-2371353177&quot;]/div[1]/picture[@class=&quot;jsx-2611454927&quot;]/img[@class=&quot;jsx-2611454927 img loaded&quot;]</value>
      <webElementGuid>394fc38f-2d56-4fdf-83f8-e61d88cb4303</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/main/div/div/div/div/div/a/div/picture/img</value>
      <webElementGuid>f4787860-7010-4d88-8864-ae2ff5fa91db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='9to9']</value>
      <webElementGuid>96b6197d-9242-4a22-bdb0-f846a26785e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/picture/img</value>
      <webElementGuid>defed634-f900-433d-8e6d-99cd008c4249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://thumbor.sirclocdn.com/unsafe/48x48/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/logo/stores/1/9to9_June_Logo_90x90_RESIZE_1.png' and @alt = '9to9']</value>
      <webElementGuid>783aea59-4724-42b1-9f6a-0c8764c2990d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
