<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_TENTANG 9to9_jsx-2611454927 img loaded</name>
   <tag></tag>
   <elementGuidId>3999b877-282e-4501-8166-9508316e1180</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.jsx-2611454927.img.loaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/main/div/div/div/div/div/a/div/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;9to9&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>696efcf8-f7ef-4fc7-8938-267664874424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-no-defer</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>83a8c6ce-bba8-4d03-9f30-4d058139b6af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://thumbor.sirclocdn.com/unsafe/48x48/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/logo/stores/1/9to9_June_Logo_90x90_RESIZE_1.png</value>
      <webElementGuid>98eef311-14ad-4656-845b-514d012b1a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>9to9</value>
      <webElementGuid>eaa341de-bda3-4fb7-8113-f8a76649b9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>61cd805b-f873-4e87-b2e3-49d5c607906d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>461ac631-591b-4010-96f7-1a45acc96555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>5a5701e8-7559-4758-834a-7d9e953a0e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-2611454927 img loaded</value>
      <webElementGuid>df6fb283-6b79-4ac0-b0e7-3bff50123260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/main[@class=&quot;jsx-2371353177 header-main-container&quot;]/div[@class=&quot;jsx-2371353177 header-main&quot;]/div[@class=&quot;jsx-2371353177 header-middle&quot;]/div[@class=&quot;jsx-2371353177 header-middle__left&quot;]/div[@class=&quot;jsx-2371353177 menu-category&quot;]/div[@class=&quot;jsx-2371353177 box header-middle__logo&quot;]/a[@class=&quot;jsx-2371353177&quot;]/div[1]/picture[@class=&quot;jsx-2611454927&quot;]/img[@class=&quot;jsx-2611454927 img loaded&quot;]</value>
      <webElementGuid>adaa001a-6827-4e7d-8f89-a387e72318fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/main/div/div/div/div/div/a/div/picture/img</value>
      <webElementGuid>762e8719-daf7-462a-84bb-95e7feb4e7d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='9to9']</value>
      <webElementGuid>34d5efed-ff45-486f-92d0-8b093e9b7c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/picture/img</value>
      <webElementGuid>3cd3cb87-6afd-45a3-9472-7bea3aea07c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://thumbor.sirclocdn.com/unsafe/48x48/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/logo/stores/1/9to9_June_Logo_90x90_RESIZE_1.png' and @alt = '9to9']</value>
      <webElementGuid>38b1f6eb-38c1-40e1-8f7c-86c68e22c43d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
