<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Subtotal_check348761</name>
   <tag></tag>
   <elementGuidId>678111a1-a50a-483f-ac5a-1887fcbf52f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.MuiButtonBase-root.MuiIconButton-root.jss292.MuiCheckbox-root.MuiCheckbox-colorPrimary.jss347.MuiIconButton-colorPrimary > span.MuiIconButton-label > input[name=&quot;check348761&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='check348761'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Lavvie Double Strap 2 In Tan 44&quot;s] >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d13c9fb-7420-4b57-be44-214fb48d813a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss295</value>
      <webElementGuid>12f10e12-7d9b-4afb-8f66-3b34ea6bdcd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>check348761</value>
      <webElementGuid>64fff482-f0d3-462a-bdaf-cb5f224df449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>348c423c-bf49-4466-be9b-180bc9082e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cdb455a6-a5a6-4ba4-90b6-cfcef9bd2bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;jss275 jss248 row&quot;]/div[@class=&quot;col-xs-12 col-sm-8 col-md-9&quot;]/div[@class=&quot;jss249&quot;]/div[@class=&quot;hidden-mobile&quot;]/div[@class=&quot;MuiPaper-root MuiTableContainer-root jss338 MuiPaper-elevation1 MuiPaper-rounded&quot;]/table[@class=&quot;MuiTable-root jss339&quot;]/tbody[@class=&quot;MuiTableBody-root&quot;]/tr[@class=&quot;MuiTableRow-root jss341&quot;]/td[@class=&quot;MuiTableCell-root MuiTableCell-body jss343 MuiTableCell-alignCenter MuiTableCell-sizeSmall&quot;]/span[@class=&quot;MuiButtonBase-root MuiIconButton-root jss292 MuiCheckbox-root MuiCheckbox-colorPrimary jss347 MuiIconButton-colorPrimary&quot;]/span[@class=&quot;MuiIconButton-label&quot;]/input[@class=&quot;jss295&quot;]</value>
      <webElementGuid>a3df5f8b-0c5f-4c65-94f2-ed483dbd4f3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='check348761'])[2]</value>
      <webElementGuid>bfcafb22-aab4-4d88-a518-f9e2ac685afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/div/div[5]/div/table/tbody/tr/td/span/span/input</value>
      <webElementGuid>247050de-5474-4795-9317-91f28938b00c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span/span/input</value>
      <webElementGuid>13c3f889-d533-4aa2-a17c-2846f7bfa7be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'check348761' and @type = 'checkbox']</value>
      <webElementGuid>b44fcc69-da87-43e8-a488-5c1db7617e1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
