<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Keranjang belanja_checkAll</name>
   <tag></tag>
   <elementGuidId>48850995-2e70-4cb6-bfaa-cc1e60660539</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;checkAll&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='checkAll']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Pilih Semua (1 item)0 produk terpilih&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7ec7ef89-14ad-4e05-8a07-b08e4d2e625b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss1138</value>
      <webElementGuid>20dd7910-a9c8-4d35-9b3e-1e450338caa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkAll</value>
      <webElementGuid>5be5b243-1421-45ec-a882-428f819fd509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f45dc1ed-f44e-4626-884e-5865d5a75e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5de8e5cf-db5e-4d58-b366-6866caf41af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;jss1118 jss1091 row&quot;]/div[@class=&quot;col-xs-12 col-sm-8 col-md-9&quot;]/div[@class=&quot;jss1092&quot;]/div[@class=&quot;jss1095&quot;]/div[@class=&quot;jss1096&quot;]/div[@class=&quot;jss1097&quot;]/label[@class=&quot;MuiFormControlLabel-root jss1129&quot;]/span[@class=&quot;MuiButtonBase-root MuiIconButton-root jss1135 MuiCheckbox-root MuiCheckbox-colorPrimary MuiIconButton-colorPrimary&quot;]/span[@class=&quot;MuiIconButton-label&quot;]/input[@class=&quot;jss1138&quot;]</value>
      <webElementGuid>a087cbb4-7ea6-4000-89ac-bfe3a0053ac8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='checkAll']</value>
      <webElementGuid>df8d93e3-240e-4ed5-a7fa-d4d3a5ea90f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/div/div/div/div/label/span/span/input</value>
      <webElementGuid>88918835-f937-4675-b4dc-bddbdb725d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>7648e513-c130-4be3-8cb5-7b7fffc5e63e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'checkAll' and @type = 'checkbox']</value>
      <webElementGuid>19ea0631-c023-4ac0-a9f0-9e20b29051e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
