<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Fashion</name>
   <tag></tag>
   <elementGuidId>e5c3d4cd-443e-4dda-8471-2a2ed2cd8f01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.jsx-1208550441.nav-item-link.avenir-black</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='nav']/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Fashion&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>61e3dc60-42a4-4477-8e84-2a3386d4b240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-1208550441 nav-item-link avenir-black</value>
      <webElementGuid>ca44c49c-f62b-4802-86bc-7f03e12d99a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>6b009c4b-4aed-44de-8c41-aa33be385357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fashion</value>
      <webElementGuid>16b70889-7c2b-4eed-ad2f-4945aa845c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav&quot;)/li[@class=&quot;jsx-1208550441 nav-item&quot;]/a[@class=&quot;jsx-1208550441 nav-item-link avenir-black&quot;]</value>
      <webElementGuid>9c30ef30-018b-4088-b63f-eed1f75149ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='nav']/li/a</value>
      <webElementGuid>033a868e-ad55-4341-b163-b2b967b2f17d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Fashion')]</value>
      <webElementGuid>68233b58-6bd7-447f-893e-b39a9a862866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HI, GUEST'])[1]/following::a[1]</value>
      <webElementGuid>897664b2-e688-4002-beb9-ae225d4a557a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::a[5]</value>
      <webElementGuid>d7ca56c1-a5bb-44e4-b78d-d05ad1d74675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fashion Muslim'])[1]/preceding::a[1]</value>
      <webElementGuid>38bcb3a1-6c86-4c80-9a73-c45de887aae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atasan Muslim Wanita'])[1]/preceding::a[2]</value>
      <webElementGuid>6b84cff6-b933-45c5-8e0e-83060be05601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fashion']/parent::*</value>
      <webElementGuid>24197cbc-726a-4869-9962-84f8ad9bb8f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/')])[7]</value>
      <webElementGuid>51db950a-df77-48b8-a2fc-ecc21a504eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a</value>
      <webElementGuid>1e858298-bd9b-47b8-b710-501ca284752a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/' and (text() = 'Fashion' or . = 'Fashion')]</value>
      <webElementGuid>108d5acc-0ea7-427d-868e-d7f302b75417</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
