<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_HUSH PUPPIES_jsx-2611454927 img image-b_93dd9c</name>
   <tag></tag>
   <elementGuidId>c1bf3d32-a5ab-48a8-94b5-8344c6ccc9b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div/div/div[2]/div/div/div[9]/div/div/a[2]/div/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(16) > .banner-image__wrapper > .hidden-mobile > a:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9263db16-b8c8-426a-bb15-776f5119dc08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-no-defer</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7340fcbf-7b41-4f76-9f64-ad999078cffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://thumbor.sirclocdn.com/unsafe/300x150/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/wysiwyg/Khaf-300x150px.jpg</value>
      <webElementGuid>7d9c63df-b40c-4f38-a478-879805109f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>d3199b93-4256-4265-b022-0d12042b92e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>a1466329-5962-4bc1-8097-41eb6a697bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>12ba8bf2-22b5-4562-997d-84c1b6f57466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>81cfe329-ef0c-4ba6-a3b6-61846361a0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-2611454927 img image-brand-pillars loaded</value>
      <webElementGuid>23c10570-850b-40cf-93c8-89ceff15a9a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;cms-container&quot;]/div[1]/div[1]/div[2]/div[@class=&quot;section about-us-section-3 about-us__wrapper max_width normal-section&quot;]/div[@class=&quot;pwa-content-brand-pillars row row-fluid&quot;]/div[@class=&quot;col-xs-6 col-md-3 banner__wrapper floating-content pwa-pillars-brand&quot;]/div[@class=&quot;banner-image__wrapper responsive-image__wrapper&quot;]/div[@class=&quot;hidden-mobile&quot;]/a[2]/div[1]/picture[@class=&quot;jsx-2611454927&quot;]/img[@class=&quot;jsx-2611454927 img image-brand-pillars loaded&quot;]</value>
      <webElementGuid>781bacad-21de-48b3-a65b-eb8f4395cd19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/div/div[2]/div/div/div[9]/div/div/a[2]/div/picture/img</value>
      <webElementGuid>5c105a11-a0f2-4ac3-93f4-74c1839fa5f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='image'])[17]</value>
      <webElementGuid>f831717d-0d1f-4b34-a093-71b866121465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/a[2]/div/picture/img</value>
      <webElementGuid>cf6b62f4-6fca-4cb0-bc3e-6fd48254eae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://thumbor.sirclocdn.com/unsafe/300x150/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/wysiwyg/Khaf-300x150px.jpg' and @alt = 'image']</value>
      <webElementGuid>99a37748-ad5e-4de3-b1c4-cb2b38a3d207</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
