<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_IDR 350,000_jsx-2611454927 img jss3481 loaded</name>
   <tag></tag>
   <elementGuidId>a1aad947-4c7e-424f-a589-9e8b1ca00dc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div[3]/div[2]/div/div/div/div[8]/div/div/div[2]/a/div/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Super Utensil Knives Set Marbella 6 Pcs&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>90f17ffa-718e-4600-a003-d7a278e673dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-no-defer</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e5f138c2-8435-4516-9e24-b8673349c79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://thumbor.sirclocdn.com/unsafe/309x324/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/catalog/product/cache/dce0cb56c455b364119abb56e91026e5/1/6/16441689860.jpeg</value>
      <webElementGuid>85ea7ba5-9f49-4c4e-b2e2-90dd7631dbed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Super Utensil Knives Set Marbella 6 Pcs</value>
      <webElementGuid>99aad2dc-75b9-4390-8c00-386cc6a6f185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>309</value>
      <webElementGuid>af67984e-05fb-422d-a792-dd876c4bc42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>782ce3a3-85d4-402c-8823-f745cc48de54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>2fb65f74-86cd-41b7-9122-8f396299f2a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-2611454927 img jss3481 loaded</value>
      <webElementGuid>e4c74945-4536-482f-b097-98ccd07480a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;jsx-402426601 jss3370&quot;]/div[@class=&quot;jss3433&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-xs-12 col-lg-12&quot;]/div[@class=&quot;jss3440&quot;]/div[@class=&quot;MuiGrid-root jss3475 grid MuiGrid-container MuiGrid-spacing-xs-1&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-6 MuiGrid-grid-sm-4 MuiGrid-grid-md-3&quot;]/div[@class=&quot;jss3477 grid-item&quot;]/div[@class=&quot;jss3478&quot;]/div[@class=&quot;jss3480&quot;]/a[@class=&quot;MuiTypography-root MuiLink-root MuiLink-underlineHover MuiTypography-colorPrimary&quot;]/div[1]/picture[@class=&quot;jsx-2611454927&quot;]/img[@class=&quot;jsx-2611454927 img jss3481 loaded&quot;]</value>
      <webElementGuid>11d021c4-0b16-4fb5-95c8-67c83e223c08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div[3]/div[2]/div/div/div/div[8]/div/div/div[2]/a/div/picture/img</value>
      <webElementGuid>d8438b03-4c47-4dfc-8a73-3f6ed2f605de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Super Utensil Knives Set Marbella 6 Pcs']</value>
      <webElementGuid>5529c5b5-4e94-4d44-b83d-5dda3406fb5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/a/div/picture/img</value>
      <webElementGuid>332dfa6f-04b3-4d44-a645-41f4bd98f77d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://thumbor.sirclocdn.com/unsafe/309x324/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/catalog/product/cache/dce0cb56c455b364119abb56e91026e5/1/6/16441689860.jpeg' and @alt = 'Super Utensil Knives Set Marbella 6 Pcs']</value>
      <webElementGuid>623fd220-79de-4412-8e0d-8413525ff543</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
