<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_DISCOUNT UP TO 89_jsx-2611454927 img loaded</name>
   <tag></tag>
   <elementGuidId>f3ad8fc6-126a-44eb-9552-9b966dcdead4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div/div[6]/div/div[2]/div/a[3]/div/div/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;image logo DISCOUNT UP TO 80%&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>94838be2-73f2-4e9d-a140-9a74f75f17fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-no-defer</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a5e80be8-1418-4b74-8129-d2e115f09228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://thumbor.sirclocdn.com/unsafe/212x106/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/banner/bannerD/logo_playboy-28-min.png</value>
      <webElementGuid>96b26c1d-4875-453b-b4f9-a40a5c370a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>80d55574-10b0-45d3-91c5-faa82dac7a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>212</value>
      <webElementGuid>58c9abce-22db-4258-8843-02261f4e36ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>106</value>
      <webElementGuid>c83a33b3-abd4-434c-b83b-a5bef5dcbde6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>36258a05-a579-4204-86cc-6810e05187af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-2611454927 img loaded</value>
      <webElementGuid>66979c3d-2a53-416e-8c21-0347f7d78931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@id=&quot;maincontent&quot;]/main[@id=&quot;maincontent&quot;]/div[2]/div[@class=&quot;pwa-homepage-content&quot;]/div[@class=&quot;pwa-selected-brand-section&quot;]/div[@class=&quot;pwa-selected-brand&quot;]/div[@class=&quot;pwa-selected-brand-container&quot;]/div[@class=&quot;pwa-selected-brand-right&quot;]/a[@class=&quot;pwa-selected-brand-list pwa-link&quot;]/div[@class=&quot;pwa-selected-brand-image&quot;]/div[1]/picture[@class=&quot;jsx-2611454927&quot;]/img[@class=&quot;jsx-2611454927 img loaded&quot;]</value>
      <webElementGuid>07d23374-1f60-441f-906a-6b830f3d23de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/div[6]/div/div[2]/div/a[3]/div/div/picture/img</value>
      <webElementGuid>6aa15a24-d596-4ad2-a3ae-a1cd464fb03e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='image'])[14]</value>
      <webElementGuid>adb38c51-4c4a-459b-9739-bbd7627ea75f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/div/div/picture/img</value>
      <webElementGuid>b575ebf3-00ed-4ebe-9966-96f5ec72f987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://thumbor.sirclocdn.com/unsafe/212x106/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/banner/bannerD/logo_playboy-28-min.png' and @alt = 'image']</value>
      <webElementGuid>b001357d-eca1-448f-8d5b-8fba98f764fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
