<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_IDR 169,000_jsx-2611454927 img jss5732 loaded</name>
   <tag></tag>
   <elementGuidId>d24c09ae-0aa6-40fb-9c90-e9c74faae871</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div[3]/div[2]/div/div/div/div[2]/div/div/div[2]/a/div/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;BOLDe Super Pump Viper&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ef4a1e06-4223-4fae-8897-db641d5c730d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-no-defer</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cf70a9f5-2119-4e1f-966f-0641b7e85bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://thumbor.sirclocdn.com/unsafe/309x324/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/catalog/product/cache/dce0cb56c455b364119abb56e91026e5/1/6/16442007290.jpeg</value>
      <webElementGuid>105597fe-cc50-4ca8-85a8-960b5897e4e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>BOLDe Super Pump Viper</value>
      <webElementGuid>3f5418e7-902f-45c4-94b2-33e8e072d5cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>309</value>
      <webElementGuid>3c332685-885b-40bf-92ac-e44aa1783546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>858f44b4-2399-4d0f-a54c-33a29450d1c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>a2f651c5-32b9-41d7-86df-b7f14fd4e9a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-2611454927 img jss5732 loaded</value>
      <webElementGuid>9ce2afa6-bc44-4cc9-aa04-38b28df3c803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;jsx-402426601 jss5594&quot;]/div[@class=&quot;jss5659&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-xs-12 col-lg-12&quot;]/div[@class=&quot;jss5666&quot;]/div[@class=&quot;MuiGrid-root jss5726 grid MuiGrid-container MuiGrid-spacing-xs-1&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-6 MuiGrid-grid-sm-4 MuiGrid-grid-md-3&quot;]/div[@class=&quot;jss5728 grid-item&quot;]/div[@class=&quot;jss5729&quot;]/div[@class=&quot;jss5731&quot;]/a[@class=&quot;MuiTypography-root MuiLink-root MuiLink-underlineHover MuiTypography-colorPrimary&quot;]/div[1]/picture[@class=&quot;jsx-2611454927&quot;]/img[@class=&quot;jsx-2611454927 img jss5732 loaded&quot;]</value>
      <webElementGuid>167ecbb0-475f-419a-b891-3cb5748e9642</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div[3]/div[2]/div/div/div/div[2]/div/div/div[2]/a/div/picture/img</value>
      <webElementGuid>4a3f116b-788f-4ba8-b5e0-ae3f33f4990f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='BOLDe Super Pump Viper']</value>
      <webElementGuid>af364a11-8233-445b-97ee-1d313327257b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/a/div/picture/img</value>
      <webElementGuid>fdffd365-e658-4fef-930b-3122c3c52e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://thumbor.sirclocdn.com/unsafe/309x324/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/catalog/product/cache/dce0cb56c455b364119abb56e91026e5/1/6/16442007290.jpeg' and @alt = 'BOLDe Super Pump Viper']</value>
      <webElementGuid>86b9c4be-3c42-4e44-8244-67468c203e96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
