<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_IDR 288,000_jsx-2611454927 img jss1243 loaded</name>
   <tag></tag>
   <elementGuidId>15b4ba26-8ff3-45a1-818f-02b277c0eeee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div[3]/div[2]/div/div/div/div[8]/div/div/div[2]/a/div/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Blanca Maxi Outer Black&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4b7130ed-b47f-4bb1-a6f7-8164c7724e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-no-defer</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>95088a88-2ca5-4fcd-b8b0-62e75e16aa0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://thumbor.sirclocdn.com/unsafe/309x324/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/catalog/product/cache/dce0cb56c455b364119abb56e91026e5/c/v/cvysa-009ot_01.jpg</value>
      <webElementGuid>8eab0b9d-cf95-47ca-8227-d6bafbe2c6da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Blanca Maxi Outer Black</value>
      <webElementGuid>f1c17c4b-d705-4e3b-8d3f-7a37ff651815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>309</value>
      <webElementGuid>6d6376f0-5ad9-4daf-b9e7-eef68111e48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>cd9ae24e-5a8a-4f58-9bcd-f95376c17d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>c258f91b-60a2-4fe8-8c50-29534e0bf600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-2611454927 img jss1243 loaded</value>
      <webElementGuid>657cbf28-173d-4368-92a7-a726939cd8ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;jsx-402426601 jss1078&quot;]/div[@class=&quot;jss1170&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-xs-12 col-lg-12&quot;]/div[@class=&quot;jss1177&quot;]/div[@class=&quot;MuiGrid-root jss1237 grid MuiGrid-container MuiGrid-spacing-xs-1&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-6 MuiGrid-grid-sm-4 MuiGrid-grid-md-3&quot;]/div[@class=&quot;jss1239 grid-item&quot;]/div[@class=&quot;jss1240&quot;]/div[@class=&quot;jss1242&quot;]/a[@class=&quot;MuiTypography-root MuiLink-root MuiLink-underlineHover MuiTypography-colorPrimary&quot;]/div[1]/picture[@class=&quot;jsx-2611454927&quot;]/img[@class=&quot;jsx-2611454927 img jss1243 loaded&quot;]</value>
      <webElementGuid>e7c4937d-9d74-4042-bd3b-7e616eae4766</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div[3]/div[2]/div/div/div/div[8]/div/div/div[2]/a/div/picture/img</value>
      <webElementGuid>e685ddf6-3a94-4dce-b404-a99f1cd2c59d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Blanca Maxi Outer Black']</value>
      <webElementGuid>0c403f30-cb0e-4185-918e-d0fb2ff88870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/a/div/picture/img</value>
      <webElementGuid>f0318047-0b33-44e0-8d2c-19d92bdfdf83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://thumbor.sirclocdn.com/unsafe/309x324/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/catalog/product/cache/dce0cb56c455b364119abb56e91026e5/c/v/cvysa-009ot_01.jpg' and @alt = 'Blanca Maxi Outer Black']</value>
      <webElementGuid>07930420-2057-4066-bfea-48af72df4a3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
