<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_IDR 189,000_jsx-2611454927 img jss480 loaded</name>
   <tag></tag>
   <elementGuidId>3263942d-2e6c-47b2-a0cc-2f4ee5c92173</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div[3]/div[2]/div/div/div/div[5]/div/div/div[2]/a/div/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Nayanika Hijab / Jilbab / Kerudung Voal Ultrafine Motif Khazan&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7da505b7-9b06-4da0-8863-b0dedd34164a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-no-defer</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bdf9c1e7-60e4-433e-8c19-d51d95b070b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://thumbor.sirclocdn.com/unsafe/309x324/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/catalog/product/cache/dce0cb56c455b364119abb56e91026e5/1/6/1695365934.6458.jpeg</value>
      <webElementGuid>4507b95d-d896-43e9-b37b-57be9bfca99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Nayanika Hijab / Jilbab / Kerudung Voal Ultrafine Motif Khazan</value>
      <webElementGuid>580326ac-bb6d-436b-a278-17fff4f850e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>309</value>
      <webElementGuid>e6b9a261-098c-465a-b76f-a5fbf49cd249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>1e68fceb-e2f4-40cc-bcee-d0b3a01ce078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>902c14bb-ada7-490f-9c56-3e5c309cafd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-2611454927 img jss480 loaded</value>
      <webElementGuid>a44e7e1d-29a9-45c9-942c-e9686a71f72f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;jsx-402426601 jss343&quot;]/div[@class=&quot;jss407&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-xs-12 col-lg-12&quot;]/div[@class=&quot;jss414&quot;]/div[@class=&quot;MuiGrid-root jss474 grid MuiGrid-container MuiGrid-spacing-xs-1&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-6 MuiGrid-grid-sm-4 MuiGrid-grid-md-3&quot;]/div[@class=&quot;jss476 grid-item&quot;]/div[@class=&quot;jss477&quot;]/div[@class=&quot;jss479&quot;]/a[@class=&quot;MuiTypography-root MuiLink-root MuiLink-underlineHover MuiTypography-colorPrimary&quot;]/div[1]/picture[@class=&quot;jsx-2611454927&quot;]/img[@class=&quot;jsx-2611454927 img jss480 loaded&quot;]</value>
      <webElementGuid>3d168d1f-9048-47c5-bd33-ab7de62e7b60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div[3]/div[2]/div/div/div/div[5]/div/div/div[2]/a/div/picture/img</value>
      <webElementGuid>a20dfc61-f220-4fa0-9ce4-c27446e63959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Nayanika Hijab / Jilbab / Kerudung Voal Ultrafine Motif Khazan']</value>
      <webElementGuid>959581ca-f86e-4a38-8846-a583c8675df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/a/div/picture/img</value>
      <webElementGuid>086a8afe-033f-44c1-8b57-1074fa62ff0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://thumbor.sirclocdn.com/unsafe/309x324/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/catalog/product/cache/dce0cb56c455b364119abb56e91026e5/1/6/1695365934.6458.jpeg' and @alt = 'Nayanika Hijab / Jilbab / Kerudung Voal Ultrafine Motif Khazan']</value>
      <webElementGuid>c5d332f7-1250-497f-b46d-b39e0095c559</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
