<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_IDR 139,000_jsx-2611454927 img jss95 loaded</name>
   <tag></tag>
   <elementGuidId>845aeb04-c4de-4434-be39-acb1c774a760</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.pwa-product-slider > div.full-width.widget-product-list > div.jsx-4220551959.carousel.jss64 > div.slick-slider.slider.slick-initialized > div.slick-list > div.slick-track > div.slick-slide.slick-active.slick-current > div > div.jss91 > div.jss92 > div.jss94 > a.MuiTypography-root.MuiLink-root.MuiLink-underlineHover.MuiTypography-colorPrimary > div > picture.jsx-2611454927 > img.jsx-2611454927.img.jss95.loaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div/div[8]/div/div[2]/div/div/div[2]/div/div/div/div/div[5]/div/div/div/div[2]/a/div/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Velove In Lime&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6f8462ea-beb3-4e9e-a443-6cc60e25a115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-no-defer</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fd9d4947-5221-44cf-8515-d83548cf55f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://thumbor.sirclocdn.com/unsafe/309x324/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/catalog/product/cache/dce0cb56c455b364119abb56e91026e5/K/F/KF10280LM-Lime-1.jpg</value>
      <webElementGuid>a429114e-2aa1-4572-bacc-3c3a60567e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Velove In Lime</value>
      <webElementGuid>7da7244a-e422-4b17-96d6-6f86a126bb98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>309</value>
      <webElementGuid>4f416e0c-19d3-4a58-ba23-30215fd75ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>d285f3ac-74a4-4b85-a840-dd06724b8523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>dba98afd-e51a-4f8e-92a5-596f18f929cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-2611454927 img jss95 loaded</value>
      <webElementGuid>24df451a-c77c-4956-b485-66e32ae314a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@id=&quot;maincontent&quot;]/main[@id=&quot;maincontent&quot;]/div[2]/div[@class=&quot;pwa-homepage-content&quot;]/div[@class=&quot;pwa-product-list-section&quot;]/div[@class=&quot;pwa-product-list&quot;]/div[@class=&quot;pwa-product-slider-container&quot;]/div[@class=&quot;pwa-product-slider-content&quot;]/div[@class=&quot;pwa-product-slider&quot;]/div[@class=&quot;full-width widget-product-list&quot;]/div[@class=&quot;jsx-4220551959 carousel jss64&quot;]/div[@class=&quot;slick-slider slider slick-initialized&quot;]/div[@class=&quot;slick-list&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active slick-current&quot;]/div[1]/div[@class=&quot;jss91&quot;]/div[@class=&quot;jss92&quot;]/div[@class=&quot;jss94&quot;]/a[@class=&quot;MuiTypography-root MuiLink-root MuiLink-underlineHover MuiTypography-colorPrimary&quot;]/div[1]/picture[@class=&quot;jsx-2611454927&quot;]/img[@class=&quot;jsx-2611454927 img jss95 loaded&quot;]</value>
      <webElementGuid>32f14ad8-d186-42bf-b981-87817fc8df30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/div[8]/div/div[2]/div/div/div[2]/div/div/div/div/div[5]/div/div/div/div[2]/a/div/picture/img</value>
      <webElementGuid>b7c1ef1a-beca-4035-9b37-5ff1ed2050a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Velove In Lime']</value>
      <webElementGuid>01cbdd27-1b7a-49f8-9bc9-e190c4670493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/div[5]/div/div/div/div[2]/a/div/picture/img</value>
      <webElementGuid>7bcb3816-e460-42b4-945e-503d59e9c572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://thumbor.sirclocdn.com/unsafe/309x324/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/catalog/product/cache/dce0cb56c455b364119abb56e91026e5/K/F/KF10280LM-Lime-1.jpg' and @alt = 'Velove In Lime']</value>
      <webElementGuid>d8385030-41a9-42d1-ba23-85964ac39e1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
