<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_IDR 639,200_jsx-2611454927 img jss881 loaded</name>
   <tag></tag>
   <elementGuidId>fe06db4b-f387-46b1-97a1-d3e6279b7e1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='pwa-flash-sale-one']/div/div[2]/div/div[2]/div/div/div/div/div[6]/div/div/div/div[2]/a/div/picture/img)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Hush Puppies Pakaian Pria Kemeja Kk Ordu&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>015cf00b-1ef7-4a7a-82fc-ff338ba91539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-no-defer</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8fbbe1b0-9604-4d57-8f70-14f95a69f9d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://thumbor.sirclocdn.com/unsafe/309x324/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/catalog/product/cache/dce0cb56c455b364119abb56e91026e5/M/B/MB28614BK-Black-1.jpg</value>
      <webElementGuid>f51c3a20-d8ea-4e13-8690-cace88dcf243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Hush Puppies Pakaian Pria Kemeja Kk Ordu</value>
      <webElementGuid>4641f56a-10c2-4e3b-af13-45676c7e16a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>309</value>
      <webElementGuid>625bfbf2-a17d-49da-8b95-b63023beed5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>76263552-a800-4030-8249-19ec679a313b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>611ca189-d928-489e-974b-8a4caebf2d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-2611454927 img jss881 loaded</value>
      <webElementGuid>9a7846e5-e92b-4165-989f-9613d68db7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@id=&quot;maincontent&quot;]/main[@id=&quot;maincontent&quot;]/div[2]/div[@class=&quot;pwa-homepage-content&quot;]/div[@id=&quot;pwa-flash-sale-one&quot;]/div[@class=&quot;pwa-product-list&quot;]/div[@class=&quot;pwa-product-slider-container&quot;]/div[@class=&quot;pwa-product-slider-full&quot;]/div[@class=&quot;full-width widget-product-list&quot;]/div[@class=&quot;jsx-4220551959 carousel jss850&quot;]/div[@class=&quot;slick-slider slider slick-initialized&quot;]/div[@class=&quot;slick-list&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active&quot;]/div[1]/div[@class=&quot;jss877&quot;]/div[@class=&quot;jss878&quot;]/div[@class=&quot;jss880&quot;]/a[@class=&quot;MuiTypography-root MuiLink-root MuiLink-underlineHover MuiTypography-colorPrimary&quot;]/div[1]/picture[@class=&quot;jsx-2611454927&quot;]/img[@class=&quot;jsx-2611454927 img jss881 loaded&quot;]</value>
      <webElementGuid>ab835dc5-8840-416b-9ee9-e6e375d6d13e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='pwa-flash-sale-one']/div/div[2]/div/div[2]/div/div/div/div/div[6]/div/div/div/div[2]/a/div/picture/img)[2]</value>
      <webElementGuid>69f22530-9ed0-4ec4-a4b5-c56d8ace2e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Hush Puppies Pakaian Pria Kemeja Kk Ordu']</value>
      <webElementGuid>527a0dc3-f70e-464c-a9ee-9f34fe03f893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div[2]/div/div/div/div/div[6]/div/div/div/div[2]/a/div/picture/img</value>
      <webElementGuid>20488e15-9a82-4478-b87e-c025721e59c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://thumbor.sirclocdn.com/unsafe/309x324/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/catalog/product/cache/dce0cb56c455b364119abb56e91026e5/M/B/MB28614BK-Black-1.jpg' and @alt = 'Hush Puppies Pakaian Pria Kemeja Kk Ordu']</value>
      <webElementGuid>e64ff894-6967-4cfb-8ec5-28c0b25d2ed4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
