<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_IDR 1,259,300_jsx-2611454927 img jss95 loaded</name>
   <tag></tag>
   <elementGuidId>663f62b0-607e-4914-92e6-58865a849886</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div/div[9]/div/div[2]/div/div/div[2]/div/div/div/div/div[6]/div/div/div/div[2]/a/div/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Primera Laces Up In Black&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>eed78b5e-d644-4752-a401-640fd40a26f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-no-defer</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>775bf710-60e5-4d3d-b011-d5abfc178cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://thumbor.sirclocdn.com/unsafe/309x324/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/catalog/product/cache/dce0cb56c455b364119abb56e91026e5/P/N/PN0084BK-Black-1.JPG</value>
      <webElementGuid>31857d4b-062c-4805-b5c7-4d4e5b6448f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Primera Laces Up In Black</value>
      <webElementGuid>7df816d2-e811-4371-afeb-1e542b6ec52c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>309</value>
      <webElementGuid>dc930e1b-922f-4731-86eb-8cb226059c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>2fa10901-344e-4790-bd87-8cfb4ba72e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>0c73ccfa-650e-47d8-b39f-d58c2a08bcef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-2611454927 img jss95 loaded</value>
      <webElementGuid>3b81e4de-853f-4e0d-aa3b-ec61f75a7680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@id=&quot;maincontent&quot;]/main[@id=&quot;maincontent&quot;]/div[2]/div[@class=&quot;pwa-homepage-content&quot;]/div[@class=&quot;pwa-product-list-section&quot;]/div[@class=&quot;pwa-product-list&quot;]/div[@class=&quot;pwa-product-slider-container&quot;]/div[@class=&quot;pwa-product-slider-content&quot;]/div[@class=&quot;pwa-product-slider&quot;]/div[@class=&quot;full-width widget-product-list&quot;]/div[@class=&quot;jsx-4220551959 carousel jss64&quot;]/div[@class=&quot;slick-slider slider slick-initialized&quot;]/div[@class=&quot;slick-list&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active&quot;]/div[1]/div[@class=&quot;jss91&quot;]/div[@class=&quot;jss92&quot;]/div[@class=&quot;jss94&quot;]/a[@class=&quot;MuiTypography-root MuiLink-root MuiLink-underlineHover MuiTypography-colorPrimary&quot;]/div[1]/picture[@class=&quot;jsx-2611454927&quot;]/img[@class=&quot;jsx-2611454927 img jss95 loaded&quot;]</value>
      <webElementGuid>d55b8566-5ac9-4540-89e2-b979118fd6ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/div[9]/div/div[2]/div/div/div[2]/div/div/div/div/div[6]/div/div/div/div[2]/a/div/picture/img</value>
      <webElementGuid>07d0176d-2839-43ea-90dd-6ffc21ae0220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Primera Laces Up In Black']</value>
      <webElementGuid>633813b0-8f9a-4b11-877e-451e60977472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[2]/div/div/div[2]/div/div/div/div/div[6]/div/div/div/div[2]/a/div/picture/img</value>
      <webElementGuid>ac6d851d-2cb5-4263-bd31-161cb40a0ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://thumbor.sirclocdn.com/unsafe/309x324/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/catalog/product/cache/dce0cb56c455b364119abb56e91026e5/P/N/PN0084BK-Black-1.JPG' and @alt = 'Primera Laces Up In Black']</value>
      <webElementGuid>79a2bca5-31c7-4662-a800-8d12ec508e00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
