<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_IDR 44,500_jsx-2611454927 img jss126 loaded</name>
   <tag></tag>
   <elementGuidId>94f2a7f1-f562-43cb-a0ce-634d0c220610</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div[3]/div[2]/div/div/div/div[5]/div/div/div[2]/a/div/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Kahf Skin Energizing And Brightening Face Wash 100 Ml&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cce764a6-9cff-46c1-86db-2b989ead39fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-no-defer</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>065d4743-d9e0-42a0-a55a-1f0c4d6b326a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://thumbor.sirclocdn.com/unsafe/309x324/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/catalog/product/cache/dce0cb56c455b364119abb56e91026e5/3/7/3766d5511533296fa4a8739b0789a9e9b4f8cff6149f90fdcc5c72b953f89342.jpeg</value>
      <webElementGuid>2f7014d9-60f7-440e-8592-31ea0aeea5f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Kahf Skin Energizing And Brightening Face Wash 100 Ml</value>
      <webElementGuid>c8f79066-2105-4d27-9243-6f14cef8a3e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>309</value>
      <webElementGuid>06ddce3f-631f-43c6-90fb-cc04885a75ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>90aac050-0355-4260-a10c-506123edd05c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>9c2a9e22-45f2-42d1-a6ad-82152a16c8cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-2611454927 img jss126 loaded</value>
      <webElementGuid>05f2a64a-7c91-4651-ab61-7af38e66f358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;jsx-402426601 jss27&quot;]/div[@class=&quot;jss77&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-xs-12 col-lg-12&quot;]/div[@class=&quot;jss84&quot;]/div[@class=&quot;MuiGrid-root jss117 grid MuiGrid-container MuiGrid-spacing-xs-1&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-6 MuiGrid-grid-sm-4 MuiGrid-grid-md-3&quot;]/div[@class=&quot;jss122 grid-item&quot;]/div[@class=&quot;jss123&quot;]/div[@class=&quot;jss125&quot;]/a[@class=&quot;MuiTypography-root MuiLink-root MuiLink-underlineHover MuiTypography-colorPrimary&quot;]/div[1]/picture[@class=&quot;jsx-2611454927&quot;]/img[@class=&quot;jsx-2611454927 img jss126 loaded&quot;]</value>
      <webElementGuid>9436ef20-5963-4b3a-b9de-b449c7fcb896</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div[3]/div[2]/div/div/div/div[5]/div/div/div[2]/a/div/picture/img</value>
      <webElementGuid>371ee12b-90f1-4fec-a4b6-bfce2d10467e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Kahf Skin Energizing And Brightening Face Wash 100 Ml']</value>
      <webElementGuid>1d665f36-90b5-4a93-ba3d-d553f950705b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/a/div/picture/img</value>
      <webElementGuid>4daf7f8a-8935-4b3b-8f34-7fb8d2a265e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://thumbor.sirclocdn.com/unsafe/309x324/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/catalog/product/cache/dce0cb56c455b364119abb56e91026e5/3/7/3766d5511533296fa4a8739b0789a9e9b4f8cff6149f90fdcc5c72b953f89342.jpeg' and @alt = 'Kahf Skin Energizing And Brightening Face Wash 100 Ml']</value>
      <webElementGuid>e737cb2d-211a-4e52-9527-08e4c5918006</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
