<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SPECIAL PRICE_jsx-2611454927 img loaded</name>
   <tag></tag>
   <elementGuidId>9c11667e-5362-442e-8f79-939c98d18528</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div/div[6]/div/div[2]/div/a[6]/div/div/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;image logo SPECIAL PRICE&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3da4cae2-77f5-4823-8ee3-d7f441df73f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-no-defer</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6850e90c-46a1-4d22-ae65-1ee8bb584cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://thumbor.sirclocdn.com/unsafe/212x106/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/wysiwyg/Makeover-300x150px.jpg</value>
      <webElementGuid>0f20b48b-147f-4029-8c23-6db7d4269872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>35c3db0f-94ba-4f5c-b398-9ffc6bf1a0ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>212</value>
      <webElementGuid>91ea2a4f-453c-49ff-9a18-a9f8654a2b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>106</value>
      <webElementGuid>42b1b391-b88f-4251-926e-6fa9c0333836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>754ad04b-86ef-4dac-9491-17de5ac11c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-2611454927 img loaded</value>
      <webElementGuid>3076dbaf-0bbc-4615-8486-db0c3a33eb74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@id=&quot;maincontent&quot;]/main[@id=&quot;maincontent&quot;]/div[2]/div[@class=&quot;pwa-homepage-content&quot;]/div[@class=&quot;pwa-selected-brand-section&quot;]/div[@class=&quot;pwa-selected-brand&quot;]/div[@class=&quot;pwa-selected-brand-container&quot;]/div[@class=&quot;pwa-selected-brand-right&quot;]/a[@class=&quot;pwa-selected-brand-list pwa-link&quot;]/div[@class=&quot;pwa-selected-brand-image&quot;]/div[1]/picture[@class=&quot;jsx-2611454927&quot;]/img[@class=&quot;jsx-2611454927 img loaded&quot;]</value>
      <webElementGuid>f3ad194b-cfb9-4864-a51b-f81876639a65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/div[6]/div/div[2]/div/a[6]/div/div/picture/img</value>
      <webElementGuid>1d712b85-6e0f-4d15-a65d-81c29006a5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='image'])[17]</value>
      <webElementGuid>79630d76-a0a1-4cfd-b016-2909b736274d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]/div/div/picture/img</value>
      <webElementGuid>3827a970-1e3f-4363-9b5d-4585e5e18bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://thumbor.sirclocdn.com/unsafe/212x106/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/wysiwyg/Makeover-300x150px.jpg' and @alt = 'image']</value>
      <webElementGuid>d15c9d12-a8f9-4150-913a-0b409799fde2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
