<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_IDR 449,500_jsx-2611454927 img jss95 loaded</name>
   <tag></tag>
   <elementGuidId>8e3ed89c-8730-4356-b3b7-24c472877ead</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='pwa-flash-sale-one']/div/div[2]/div/div[2]/div/div/div/div/div[5]/div/div/div/div[2]/a/div/picture/img)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Obermain Pakaian Pria Long Pants Edwin&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8e1cd3d7-1e30-45a0-a515-93ea5046caac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-no-defer</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a4b485f9-109e-41e4-9b51-e35be68421a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://thumbor.sirclocdn.com/unsafe/309x324/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/catalog/product/cache/dce0cb56c455b364119abb56e91026e5/O/P/OPH25017DB-Dark_Brown-1.jpg</value>
      <webElementGuid>c36b7319-841c-43a1-8fe6-52168ea01276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Obermain Pakaian Pria Long Pants Edwin</value>
      <webElementGuid>d4be7484-875e-463a-a42d-36b385606ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>309</value>
      <webElementGuid>d9806c9e-2023-41c9-801e-a701e966fe78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>472b1511-9da8-4179-9422-130fb6266b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>b43b5ccd-c1f8-47d3-9f90-3a578d0206d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-2611454927 img jss95 loaded</value>
      <webElementGuid>58009743-8f62-4250-92d2-e0c24e982dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@id=&quot;maincontent&quot;]/main[@id=&quot;maincontent&quot;]/div[2]/div[@class=&quot;pwa-homepage-content&quot;]/div[@id=&quot;pwa-flash-sale-one&quot;]/div[@class=&quot;pwa-product-list&quot;]/div[@class=&quot;pwa-product-slider-container&quot;]/div[@class=&quot;pwa-product-slider-full&quot;]/div[@class=&quot;full-width widget-product-list&quot;]/div[@class=&quot;jsx-4220551959 carousel jss64&quot;]/div[@class=&quot;slick-slider slider slick-initialized&quot;]/div[@class=&quot;slick-list&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active slick-current&quot;]/div[1]/div[@class=&quot;jss91&quot;]/div[@class=&quot;jss92&quot;]/div[@class=&quot;jss94&quot;]/a[@class=&quot;MuiTypography-root MuiLink-root MuiLink-underlineHover MuiTypography-colorPrimary&quot;]/div[1]/picture[@class=&quot;jsx-2611454927&quot;]/img[@class=&quot;jsx-2611454927 img jss95 loaded&quot;]</value>
      <webElementGuid>86e029c5-a94e-4381-8082-7b43d304dc29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='pwa-flash-sale-one']/div/div[2]/div/div[2]/div/div/div/div/div[5]/div/div/div/div[2]/a/div/picture/img)[2]</value>
      <webElementGuid>80aef68a-ca3b-4ff3-a397-850dd814878d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Obermain Pakaian Pria Long Pants Edwin']</value>
      <webElementGuid>4b42b4ca-b505-45fe-b557-b2393435987e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div[2]/div/div/div/div/div[5]/div/div/div/div[2]/a/div/picture/img</value>
      <webElementGuid>62ca5267-97e3-4335-ace8-cfa4984dabf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://thumbor.sirclocdn.com/unsafe/309x324/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/catalog/product/cache/dce0cb56c455b364119abb56e91026e5/O/P/OPH25017DB-Dark_Brown-1.jpg' and @alt = 'Obermain Pakaian Pria Long Pants Edwin']</value>
      <webElementGuid>cb27340a-91e2-4eca-9c1f-ca822751545d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
