<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_IDR 799,000_jsx-2611454927 img jss1639 loaded</name>
   <tag></tag>
   <elementGuidId>d4deb53a-dd0f-490c-b220-6a987785f6dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='pwa-flash-sale-one']/div/div[2]/div/div[2]/div/div/div/div/div[9]/div/div/div/div[2]/a/div/picture/img)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Hush Puppies Pakaian Wanita Dress Kk Shakirat 2&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>39135b19-8a5f-4755-a6c3-887cab44c467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-no-defer</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>62a55604-c2dc-4651-898f-7ef6837102a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://thumbor.sirclocdn.com/unsafe/309x324/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/catalog/product/cache/dce0cb56c455b364119abb56e91026e5/L/G/LG28113NV-Navy-1.jpg</value>
      <webElementGuid>17313744-5443-482b-bcfc-2308ec1a2bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Hush Puppies Pakaian Wanita Dress Kk Shakirat 2</value>
      <webElementGuid>1e335a5f-167c-48dc-ad46-298fa5435aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>309</value>
      <webElementGuid>70205951-6769-4ca3-abbf-22454ee4cb0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>23c9c117-e02e-44ab-8034-23a9f618c558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>2854dc38-e775-4171-82be-4d7f859c3883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-2611454927 img jss1639 loaded</value>
      <webElementGuid>b66bd4fc-7aa6-4213-86fd-d0f347413fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@id=&quot;maincontent&quot;]/main[@id=&quot;maincontent&quot;]/div[2]/div[@class=&quot;pwa-homepage-content&quot;]/div[@id=&quot;pwa-flash-sale-one&quot;]/div[@class=&quot;pwa-product-list&quot;]/div[@class=&quot;pwa-product-slider-container&quot;]/div[@class=&quot;pwa-product-slider-full&quot;]/div[@class=&quot;full-width widget-product-list&quot;]/div[@class=&quot;jsx-4220551959 carousel jss1608&quot;]/div[@class=&quot;slick-slider slider slick-initialized&quot;]/div[@class=&quot;slick-list&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active&quot;]/div[1]/div[@class=&quot;jss1635&quot;]/div[@class=&quot;jss1636&quot;]/div[@class=&quot;jss1638&quot;]/a[@class=&quot;MuiTypography-root MuiLink-root MuiLink-underlineHover MuiTypography-colorPrimary&quot;]/div[1]/picture[@class=&quot;jsx-2611454927&quot;]/img[@class=&quot;jsx-2611454927 img jss1639 loaded&quot;]</value>
      <webElementGuid>f6156ec2-bfbc-4a0c-a376-50a2e5863465</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='pwa-flash-sale-one']/div/div[2]/div/div[2]/div/div/div/div/div[9]/div/div/div/div[2]/a/div/picture/img)[2]</value>
      <webElementGuid>2e2426af-39b5-4562-a39f-9fbe490d596e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Hush Puppies Pakaian Wanita Dress Kk Shakirat 2'])[2]</value>
      <webElementGuid>5eee27c2-daeb-4ba3-a47c-a222b13199b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div[2]/div/div/div/div/div[9]/div/div/div/div[2]/a/div/picture/img</value>
      <webElementGuid>a1e0ac1b-e540-465a-9d8c-f975fa40c05a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://thumbor.sirclocdn.com/unsafe/309x324/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/catalog/product/cache/dce0cb56c455b364119abb56e91026e5/L/G/LG28113NV-Navy-1.jpg' and @alt = 'Hush Puppies Pakaian Wanita Dress Kk Shakirat 2']</value>
      <webElementGuid>cef4c3ce-3048-4929-8413-32fdc6da95b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
