<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Lihat Semua_jsx-2611454927 img loaded</name>
   <tag></tag>
   <elementGuidId>44e7e26d-c5a7-4b3e-880f-d25321e65bf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.pwa-selected-brand-image > div > picture.jsx-2611454927 > img.jsx-2611454927.img.loaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div/div[6]/div/div[2]/div/a/div/div/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;image logo DISCOUNT UP TO 80%&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2eaa4588-049e-41c1-b858-970750bcff9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-no-defer</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f3d165fa-0a71-4b5d-8e7f-082377713417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://thumbor.sirclocdn.com/unsafe/212x106/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/banner/bannerD/logo_hp_2-min.png</value>
      <webElementGuid>0095b391-9b2a-438c-b612-1df90a0179cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>fc472664-c476-4dd2-aade-682d18f1c101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>212</value>
      <webElementGuid>b0366040-e882-4768-8c86-28222ca4f7a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>106</value>
      <webElementGuid>5bbd3405-ee17-456c-ac7c-4d6e332b89b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>d1ec4015-f542-4699-87e5-4177afb06588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-2611454927 img loaded</value>
      <webElementGuid>f0bafd02-863b-4fd2-8cd6-0b1ec8475307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@id=&quot;maincontent&quot;]/main[@id=&quot;maincontent&quot;]/div[2]/div[@class=&quot;pwa-homepage-content&quot;]/div[@class=&quot;pwa-selected-brand-section&quot;]/div[@class=&quot;pwa-selected-brand&quot;]/div[@class=&quot;pwa-selected-brand-container&quot;]/div[@class=&quot;pwa-selected-brand-right&quot;]/a[@class=&quot;pwa-selected-brand-list pwa-link&quot;]/div[@class=&quot;pwa-selected-brand-image&quot;]/div[1]/picture[@class=&quot;jsx-2611454927&quot;]/img[@class=&quot;jsx-2611454927 img loaded&quot;]</value>
      <webElementGuid>c016cbd8-92c8-49cc-9c5e-8fc5f4ff322b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/div[6]/div/div[2]/div/a/div/div/picture/img</value>
      <webElementGuid>3dfba2d0-ffcc-4941-8832-d2b3f435bf3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='image'])[12]</value>
      <webElementGuid>3e55a5b6-1030-4b30-bc86-21bd70ddae18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/div/div/picture/img</value>
      <webElementGuid>6dda9507-ef00-4e7d-8761-87f962adc29c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://thumbor.sirclocdn.com/unsafe/212x106/filters:format(jpeg):quality(80)/magento.9to9.co.id/media/banner/bannerD/logo_hp_2-min.png' and @alt = 'image']</value>
      <webElementGuid>cc9eb3ef-5e1c-4241-80ce-03c1f2926665</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
