<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Talk with Nina_popup_1744428956467</name>
   <tag></tag>
   <elementGuidId>b51761c2-c82e-4890-a7a5-d9e186760a2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#snap-midtrans</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='snap-midtrans']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;popup_1744428956467&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d23a1115-4371-45a8-85af-f9cacccea74a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://app.midtrans.com/snap/v4/popup?origin_host=https://9to9.co.id&amp;client_key=Mid-client-FDfzlfyZ50nup6SV#/</value>
      <webElementGuid>9c975e01-25fc-46aa-ad4c-0e06a5bc7ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>snap-midtrans</value>
      <webElementGuid>596176f6-0bdd-4f47-a31d-93479c5d895c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>popup_1744428956467</value>
      <webElementGuid>6e0f5c31-fac2-4fc3-be19-5ced65679bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;snap-midtrans&quot;)</value>
      <webElementGuid>b7bab6ba-f3f7-497a-9241-81a2ade4e03b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='snap-midtrans']</value>
      <webElementGuid>25cb260b-a491-483a-95b5-12098b5446e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[14]</value>
      <webElementGuid>29ca4b59-d802-4559-b555-19287a5d0def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://app.midtrans.com/snap/v4/popup?origin_host=https://9to9.co.id&amp;client_key=Mid-client-FDfzlfyZ50nup6SV#/' and @id = 'snap-midtrans' and @name = 'popup_1744428956467']</value>
      <webElementGuid>dd99bc5a-8ebd-4101-ab52-a4d545ebffb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
