<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Report a map error_newsletter</name>
   <tag></tag>
   <elementGuidId>f07f78db-d0ee-418e-8026-992873326a2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addressForm-confirmPinPoint-checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addressForm-confirmPinPoint-checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Saya yakin bahwa pinpoint pada peta cocok dengan alamat saya. Segala bentuk kesalahan dalam pengiriman dikarenakan kesalahan pada pemilihan pinpoint bukan menjadi tanggung jawab marketplace.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d2eef5f-a940-4590-9d5f-8cebb3af2849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss1351</value>
      <webElementGuid>17fff3e0-e2b6-4a18-ba8a-a5494d4d05e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressForm-confirmPinPoint-checkbox</value>
      <webElementGuid>bada76da-31fb-41a6-9230-b0ccfecb4e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>newsletter</value>
      <webElementGuid>98af7f5a-79a7-4bc9-b076-d2b054c904a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6b83ad9a-1e46-489b-94ff-a3f149b3eb7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>32b7438f-3e86-4e03-8134-4eb5bb880195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0a169096-6927-4301-a86c-2a1b39c31c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressForm-confirmPinPoint-checkbox&quot;)</value>
      <webElementGuid>a7c2296c-2d6a-4c81-a8bc-0ce77e41db10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressForm-confirmPinPoint-checkbox']</value>
      <webElementGuid>6b10c788-c8fc-4ee7-a39c-4f5f7706d246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formAddressInputContainer']/form/div[13]/label/span/span/input</value>
      <webElementGuid>6e6858cb-3238-4ec3-ba97-2d6a676d1983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/label/span/span/input</value>
      <webElementGuid>88ecc92f-8b0d-4587-81da-cae52b2e6502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addressForm-confirmPinPoint-checkbox' and @name = 'newsletter' and @type = 'checkbox']</value>
      <webElementGuid>fce3773d-6f87-4081-943a-78bfcf5d8b3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
