<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Belakang_lastname</name>
   <tag></tag>
   <elementGuidId>da1f4350-0ecb-4a38-956b-a40f1962a623</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addressForm-lastName-textField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addressForm-lastName-textField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#addressForm-lastName-textField</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc5406d5-8e88-4f4e-894d-6c34046c655e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>34d989db-092f-4c8f-97a9-7119b57b78fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>1e1638f4-b029-42d3-a5ca-38523246abdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressForm-lastName-textField</value>
      <webElementGuid>cb30574f-b49d-4265-aa95-73fc2940846f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lastname</value>
      <webElementGuid>019cdf0c-f73c-4409-a1f1-edb276553c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fd48d663-a416-4232-88c1-2c71f10e1d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input</value>
      <webElementGuid>ed8d510f-52b1-47d4-b034-d9f4d5dcab19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressForm-lastName-textField&quot;)</value>
      <webElementGuid>09431416-eef2-40ff-8a79-f02938a32c46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressForm-lastName-textField']</value>
      <webElementGuid>91f20dea-4a2e-49bf-bc56-eb96a506e3ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formAddressInputContainer']/form/div[2]/div/input</value>
      <webElementGuid>7367ca65-6f1f-47ec-af47-8b6156f836e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>e7231cee-bb8d-4deb-9256-a1c12b9e77cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addressForm-lastName-textField' and @name = 'lastname' and @type = 'text']</value>
      <webElementGuid>e21f9b6a-0810-43df-a849-f8ba41f712d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
