<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Anteraja_mui-96843</name>
   <tag></tag>
   <elementGuidId>6d1d5f34-aa41-47b7-adf1-dd998c8719ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;mui-96843&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='mui-96843']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=radio[name=&quot;REG - IDR 0&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f6c07be-cd7e-4319-861c-1ae45a682dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss542</value>
      <webElementGuid>1586817a-1bb6-46cc-a043-061691f48cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b4d18136-7cae-47a2-8217-74c31c2e85c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>REG - anteraja - PTT</value>
      <webElementGuid>db3c6bb9-5736-4a6c-8acc-fb9eab368dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mui-96843</value>
      <webElementGuid>e9d10d32-a3c7-4eca-80c0-ee9143c16985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkoutShipping&quot;)/div[@class=&quot;jss416&quot;]/div[@class=&quot;MuiPaper-root MuiAccordion-root jss573 Mui-expanded jss574 MuiAccordion-rounded MuiPaper-elevation1 MuiPaper-rounded&quot;]/div[@class=&quot;MuiCollapse-container MuiCollapse-entered&quot;]/div[@class=&quot;MuiCollapse-wrapper&quot;]/div[@class=&quot;MuiCollapse-wrapperInner&quot;]/div[@id=&quot;panel1d-content&quot;]/div[@class=&quot;MuiAccordionDetails-root jss578&quot;]/fieldset[@class=&quot;MuiFormControl-root&quot;]/div[@class=&quot;MuiFormGroup-root&quot;]/div[1]/div[@class=&quot;MuiPaper-root MuiAccordion-root jss573 Mui-expanded jss574 MuiAccordion-rounded MuiPaper-elevation1 MuiPaper-rounded&quot;]/div[@class=&quot;MuiCollapse-container MuiCollapse-entered&quot;]/div[@class=&quot;MuiCollapse-wrapper&quot;]/div[@class=&quot;MuiCollapse-wrapperInner&quot;]/div[@id=&quot;panel-Anteraja&quot;]/div[@class=&quot;MuiAccordionDetails-root jss578&quot;]/label[@class=&quot;MuiFormControlLabel-root&quot;]/span[@class=&quot;MuiButtonBase-root MuiIconButton-root jss539 MuiRadio-root MuiRadio-colorSecondary MuiIconButton-colorSecondary&quot;]/span[@class=&quot;MuiIconButton-label&quot;]/input[@class=&quot;jss542&quot;]</value>
      <webElementGuid>d88675cf-c4e0-4d69-b71c-552e08ddc764</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='mui-96843']</value>
      <webElementGuid>fd02caad-899b-41f9-99b1-d98f48b6bbf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-Anteraja']/div/label/span/span/input</value>
      <webElementGuid>c884d1ed-56e8-4cfa-9ca8-26f0a5578e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>89b12921-21e3-4fe1-b885-4c1411666c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'mui-96843']</value>
      <webElementGuid>a7138975-3808-4187-8877-c8961a692a3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
