<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Transfer bank_radio</name>
   <tag></tag>
   <elementGuidId>d5ff7f98-5b7a-49db-858c-49d12d74ea6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;radio&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='radio']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Transfer bank&quot;i >> internal:role=radio >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9aa39f6-1071-4c02-9447-32c7c2b5e07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss542</value>
      <webElementGuid>56f02558-7fde-47bb-9375-581357e7d49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>28702d42-e0de-41cd-9bf9-fcb632f8cea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>99fb6412-56ce-40aa-bbbc-bd24f5a7c4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkoutPayment&quot;)/div[1]/div[1]/div[@class=&quot;jss416&quot;]/div[@class=&quot;MuiPaper-root MuiAccordion-root jss521 Mui-expanded jss522 MuiAccordion-rounded MuiPaper-elevation1 MuiPaper-rounded&quot;]/div[@class=&quot;MuiCollapse-container MuiCollapse-entered&quot;]/div[@class=&quot;MuiCollapse-wrapper&quot;]/div[@class=&quot;MuiCollapse-wrapperInner&quot;]/div[@id=&quot;panel1d-content&quot;]/div[@class=&quot;MuiAccordionDetails-root jss526&quot;]/div[1]/div[@class=&quot;jss527&quot;]/div[@class=&quot;MuiFormGroup-root jss528 jss530&quot;]/div[@id=&quot;checkoutRadioItem&quot;]/span[@class=&quot;MuiButtonBase-root MuiIconButton-root jss539 MuiRadio-root&quot;]/span[@class=&quot;MuiIconButton-label&quot;]/input[@class=&quot;jss542&quot;]</value>
      <webElementGuid>80f6020f-d180-40e9-8374-b9c99b58dd4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='radio']</value>
      <webElementGuid>4913e57d-5e60-4875-a9b7-a47467f722fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkoutRadioItem']/span/span/input</value>
      <webElementGuid>df003f00-9163-437c-bbc5-60af3cf927fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/span/input</value>
      <webElementGuid>43786ab4-a260-4b2a-af09-7d885246d66a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'radio' and @type = 'radio']</value>
      <webElementGuid>77a5eda0-6a7b-4e76-95c9-b9739af5f28e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>68cc0ce1-3558-4a64-8404-48d2f85577ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
