<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Detail Alamat_addressDetail</name>
   <tag></tag>
   <elementGuidId>6d607218-bda9-4b1c-b5c3-930f84852096</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addressForm-addressDetail-textField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addressForm-addressDetail-textField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Masukan alamat detail anda&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c99055c7-8028-4167-854c-99cb84919a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0f57092c-eaec-42b7-9dee-c033a7f6e61c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>54f1bbb1-4c90-4759-a3f5-07ac16b7a60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressForm-addressDetail-textField</value>
      <webElementGuid>899a8ffa-98c3-441c-9417-4c546099e3b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addressDetail</value>
      <webElementGuid>331cfcef-387e-4b51-99dc-2f9366b121c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan alamat detail anda</value>
      <webElementGuid>982bf7b4-007a-49e0-b29b-6159f6d4b083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>83aeadc9-af2b-470f-a870-7afdde255357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input pac-target-input</value>
      <webElementGuid>e9e13209-da4f-4ad8-b161-f802a3482108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressForm-addressDetail-textField&quot;)</value>
      <webElementGuid>b5193f5b-0853-424a-9d9b-63329b68ce17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressForm-addressDetail-textField']</value>
      <webElementGuid>9fb353b0-a01f-43a1-855e-4fa8b4ac78ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formAddressInputContainer']/form/div[10]/div/div/div/input</value>
      <webElementGuid>13bc1cf6-8024-4a04-af38-5f945e4e68d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/input</value>
      <webElementGuid>15dbd095-ae41-4db6-b260-9b6bc64b0eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addressForm-addressDetail-textField' and @name = 'addressDetail' and @placeholder = 'Masukan alamat detail anda' and @type = 'text']</value>
      <webElementGuid>79d29e87-c872-4e5e-b748-c29def115cda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
