<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Fashion</name>
   <tag></tag>
   <elementGuidId>40ea24f6-bcf9-42da-a1d9-135c60000251</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.jsx-1208550441.nav-item-link.avenir-black</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='nav']/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Fashion&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ad70745c-4015-40b9-8553-4a3666d7155a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-1208550441 nav-item-link avenir-black</value>
      <webElementGuid>2667560d-fd31-427d-b0fa-b04536790ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/kalila-organza-outer-light-orange</value>
      <webElementGuid>a6d4e6fb-d036-4528-b1d7-e9779642682f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fashion</value>
      <webElementGuid>f12b6767-1356-4834-a944-2cbf8ee1b9f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav&quot;)/li[@class=&quot;jsx-1208550441 nav-item&quot;]/a[@class=&quot;jsx-1208550441 nav-item-link avenir-black&quot;]</value>
      <webElementGuid>c2775d96-cd22-4f62-a782-1967edeb978e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='nav']/li/a</value>
      <webElementGuid>01aeec8d-7d4e-42ac-8b8e-68f6cc8c244b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Fashion')]</value>
      <webElementGuid>b241455b-f193-41dc-8534-a21dca371cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HI, GUEST'])[1]/following::a[1]</value>
      <webElementGuid>8c7994bf-280a-44a6-9189-d04b5190e13a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::a[5]</value>
      <webElementGuid>15837eec-c2ed-4bce-b9b8-95a1030e516a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fashion Muslim'])[1]/preceding::a[1]</value>
      <webElementGuid>96a14151-4108-4d19-ac1f-91554fa0cda0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atasan Muslim Wanita'])[1]/preceding::a[2]</value>
      <webElementGuid>c49b0393-85e5-4765-b989-ff62faff6f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fashion']/parent::*</value>
      <webElementGuid>8b40e889-4e55-4dca-959a-abb5ebe112fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/kalila-organza-outer-light-orange')]</value>
      <webElementGuid>0010316f-fce3-49dd-afcd-de174188591f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a</value>
      <webElementGuid>118dc614-4ae0-4ec9-b258-2b33b0c83389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/kalila-organza-outer-light-orange' and (text() = 'Fashion' or . = 'Fashion')]</value>
      <webElementGuid>5faa3277-b813-4510-9a80-e57be9c20de5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
