<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cutleries</name>
   <tag></tag>
   <elementGuidId>e83163c5-1ca6-447a-817f-7cfbac14dae5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='nav']/li[2]/div/div/div[7]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Cutleries&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>11bfa5b9-6631-4966-bc33-7675fbcb118a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-1208550441 avenir-black</value>
      <webElementGuid>593c5513-83c6-4a1f-a6a5-3407d1266b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/home-living/cutleries</value>
      <webElementGuid>4f1c75f2-ac9f-4abe-9b18-7e23f700f383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cutleries</value>
      <webElementGuid>2e31b962-49ff-4ddc-962c-e42b0404998f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav&quot;)/li[@class=&quot;jsx-1208550441 nav-item&quot;]/div[@class=&quot;jsx-1208550441 mega-menu row&quot;]/div[@class=&quot;jsx-1208550441 nav-column row col-lg-12 col-md-12 col-sm-12&quot;]/div[@class=&quot;jsx-1208550441 list-item col-lg-3 col-md-4 col-sm-6&quot;]/a[@class=&quot;jsx-1208550441 avenir-black&quot;]</value>
      <webElementGuid>0e7de266-0861-4275-966f-60a27aac0a10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='nav']/li[2]/div/div/div[7]/a</value>
      <webElementGuid>d9260c7a-de3c-4578-9099-18116a5891d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cutleries')]</value>
      <webElementGuid>3d09b97b-d977-4721-8f70-fc6b773ce729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Handuk Mandi'])[1]/following::a[1]</value>
      <webElementGuid>dec0c111-4535-4d3b-a86e-6d38b929daff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kamar Mandi'])[1]/following::a[2]</value>
      <webElementGuid>eb735a31-a404-4828-89ac-077d9e576738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fragrance'])[1]/preceding::a[1]</value>
      <webElementGuid>3ecdffb2-48d7-4af3-b1b3-433a0d95c8c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Koper'])[1]/preceding::a[2]</value>
      <webElementGuid>bc03dbbc-2da6-448c-8177-371f00f04efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cutleries']/parent::*</value>
      <webElementGuid>d022913c-02b2-43e1-983e-5bfaad5ffc8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/home-living/cutleries')]</value>
      <webElementGuid>9076c266-4338-431b-a52c-8c594f9904fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/a</value>
      <webElementGuid>b051b776-9735-4a2a-8672-356db3d283c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/home-living/cutleries' and (text() = 'Cutleries' or . = 'Cutleries')]</value>
      <webElementGuid>5f5f8784-11e3-413f-873e-9d76e98b6c72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
