<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Aksesori</name>
   <tag></tag>
   <elementGuidId>c28f6647-1fbc-4088-88f6-e28eec004c72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='nav']/li[2]/div/div/div[2]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Aksesori&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ae1226cc-70ac-49bf-a418-37ac4e860f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-1208550441 </value>
      <webElementGuid>476e6167-3278-4957-bb85-ed2710cea764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/home-living/alat-dapur/asesoris</value>
      <webElementGuid>eacc952e-9d7f-447d-8112-cc666553e61c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aksesori</value>
      <webElementGuid>48776e5e-69b5-4433-bb22-eafe78abb714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav&quot;)/li[@class=&quot;jsx-1208550441 nav-item&quot;]/div[@class=&quot;jsx-1208550441 mega-menu row&quot;]/div[@class=&quot;jsx-1208550441 nav-column row col-lg-12 col-md-12 col-sm-12&quot;]/div[@class=&quot;jsx-1208550441 list-item col-lg-3 col-md-4 col-sm-6&quot;]/ul[@class=&quot;jsx-1208550441 list-item__menu&quot;]/li[@class=&quot;jsx-1208550441&quot;]/a[@class=&quot;jsx-1208550441&quot;]</value>
      <webElementGuid>68bfece1-13d8-4464-a97d-127195419e00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='nav']/li[2]/div/div/div[2]/ul/li/a</value>
      <webElementGuid>25a66472-0718-4d7c-b186-4d6178786d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Aksesori')])[4]</value>
      <webElementGuid>3ee5a763-e95b-4b8c-b388-62e7221d0d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alat Dapur'])[1]/following::a[1]</value>
      <webElementGuid>c27382ef-a2fa-4ac4-be7c-cc23b8711842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vacuum Cleaner'])[1]/following::a[2]</value>
      <webElementGuid>ddd134a9-9878-467b-af6f-01e5fe0992c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Botol Minum'])[1]/preceding::a[1]</value>
      <webElementGuid>d33f894a-6df2-45c9-acf7-03c0f33d704b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grill'])[1]/preceding::a[2]</value>
      <webElementGuid>5590403f-495b-4b12-a3af-282a3d68638c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aksesori']/parent::*</value>
      <webElementGuid>dd8b84be-ddc4-49aa-9e57-7eeb1a58b7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/home-living/alat-dapur/asesoris')]</value>
      <webElementGuid>3d2fa862-ef9d-4f41-b371-44b8dc67c190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div[2]/ul/li/a</value>
      <webElementGuid>7fe52c04-c990-4cc6-80b1-32aaa16473dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/home-living/alat-dapur/asesoris' and (text() = 'Aksesori' or . = 'Aksesori')]</value>
      <webElementGuid>36b40a90-5253-4162-a076-9d3968b2a279</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
